{{- if .Values.secrets.api.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.api.name | quote }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  API_JWT_SECRET: {{ .Values.secrets.api.jwtSecret | quote }}
  API_KEYS: {{ .Values.secrets.api.apiKeys | quote }}
{{- end }}

