{{- if and .Values.api.enabled .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stateset-agents.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "stateset-agents.fullname" . }}-api
{{- end }}
