{{- if .Values.secrets.wandb.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.trainingJob.wandbSecretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  api_key: {{ .Values.secrets.wandb.token | b64enc }}
{{- end }}
