name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize agent with '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: python
      placeholder: |
        import asyncio
        from stateset_agents import MultiTurnAgent, AgentConfig

        async def main():
            agent = MultiTurnAgent(AgentConfig(model_name="gpt2"))
            await agent.initialize()
            # Your code that triggers the bug

        asyncio.run(main())
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs
      render: shell
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: StateSet Agents Version
      description: What version of StateSet Agents are you running?
      options:
        - 0.5.0 (latest)
        - 0.4.0
        - 0.3.4
        - 0.3.3
        - 0.3.2
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.10.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      options:
        - pip install stateset-agents
        - pip install from GitHub
        - Development install (pip install -e .)
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Installed Dependencies
      description: Output of `pip list | grep -E "(stateset|torch|transformers|trl)"`
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
