apiVersion: v1
kind: Secret
metadata:
  name: hf-secret
  namespace: stateset-agents
type: Opaque
data:
  # Base64 encoded token
  # echo -n "hf_xxx" | base64
  hf_token: <BASE64_ENCODED_HUGGING_FACE_HUB_TOKEN>
