apiVersion: v1
kind: Secret
metadata:
  name: grpo-framework-secrets
  namespace: grpo-framework
type: Opaque
data:
  # Base64 encoded secrets
  POSTGRES_USER: Z3Jwbw==  # grpo
  POSTGRES_PASSWORD: Z3Jwb19wYXNzd29yZA==  # grpo_password
  OPENAI_API_KEY: ""  # Base64 encoded OpenAI API key
  ANTHROPIC_API_KEY: ""  # Base64 encoded Anthropic API key
  HUGGINGFACE_API_KEY: ""  # Base64 encoded HuggingFace API key
  JWT_SECRET: Z3Jwb19qd3Rfc2VjcmV0XzIwMjQ=  # grpo_jwt_secret_2024
  
  # Database URLs
  DATABASE_URL: cG9zdGdyZXNxbDovL2dycG86Z3Jwb19wYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZ3Jwb19mcmFtZXdvcms=
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=