apiVersion: v1
kind: Secret
metadata:
  name: grpo-framework-secrets
  namespace: grpo-framework
type: Opaque
# NOTE:
# - Copy this file to secret.yaml and replace placeholders with base64-encoded values.
# - Do NOT commit the filled secret.yaml to git.
# - Helper: echo -n "plain_text" | base64
data:
  # Base64 encoded secrets
  POSTGRES_USER: <BASE64_ENCODED_POSTGRES_USER>          # e.g., echo -n "grpo" | base64
  POSTGRES_PASSWORD: <BASE64_ENCODED_POSTGRES_PASSWORD>  # required
  OPENAI_API_KEY: <BASE64_ENCODED_OPENAI_API_KEY>        # optional
  ANTHROPIC_API_KEY: <BASE64_ENCODED_ANTHROPIC_API_KEY>  # optional
  HUGGINGFACE_API_KEY: <BASE64_ENCODED_HUGGINGFACE_API_KEY>  # optional
  JWT_SECRET: <BASE64_ENCODED_JWT_SECRET>                # required

  # Base64 encoded connection URLs
  DATABASE_URL: <BASE64_ENCODED_DATABASE_URL>
  REDIS_URL: <BASE64_ENCODED_REDIS_URL>

