apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stateset-models-pvc
  namespace: stateset-agents
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: standard-rwo
