global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'grpo-framework'
    static_configs:
      - targets: ['grpo-framework:8001']
    scrape_interval: 10s
    metrics_path: /metrics
    
  - job_name: 'grpo-training'
    static_configs:
      - targets: ['grpo-framework:8002']
    scrape_interval: 30s
    metrics_path: /training/metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093