// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryItem {
    #[prost(int64, tag = "1")]
    pub inventory_item_id: i64,
    #[prost(string, tag = "2")]
    pub item_number: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub primary_uom_code: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub organization_id: i64,
    #[prost(message, optional, tag = "6")]
    pub quantities: ::core::option::Option<InventoryQuantities>,
    #[prost(message, repeated, tag = "7")]
    pub locations: ::prost::alloc::vec::Vec<InventoryLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryQuantities {
    /// Using string for Decimal precision
    #[prost(string, tag = "1")]
    pub on_hand: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub allocated: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub available: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryLocation {
    #[prost(int32, tag = "1")]
    pub location_id: i32,
    #[prost(string, tag = "2")]
    pub location_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub quantities: ::core::option::Option<InventoryQuantities>,
    #[prost(message, optional, tag = "4")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdjustInventoryRequest {
    #[prost(int32, tag = "3")]
    pub location_id: i32,
    /// Using string for Decimal precision
    #[prost(string, tag = "4")]
    pub quantity_delta: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub idempotency_key: ::prost::alloc::string::String,
    #[prost(oneof = "adjust_inventory_request::Identifier", tags = "1, 2")]
    pub identifier: ::core::option::Option<adjust_inventory_request::Identifier>,
}
/// Nested message and enum types in `AdjustInventoryRequest`.
pub mod adjust_inventory_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Identifier {
        #[prost(int64, tag = "1")]
        InventoryItemId(i64),
        #[prost(string, tag = "2")]
        ItemNumber(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdjustInventoryResponse {
    #[prost(message, optional, tag = "1")]
    pub location_balance: ::core::option::Option<InventoryLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReserveInventoryRequest {
    #[prost(int32, tag = "3")]
    pub location_id: i32,
    /// Using string for Decimal precision
    #[prost(string, tag = "4")]
    pub quantity: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reference_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub reference_type: ::prost::alloc::string::String,
    #[prost(oneof = "reserve_inventory_request::Identifier", tags = "1, 2")]
    pub identifier: ::core::option::Option<reserve_inventory_request::Identifier>,
}
/// Nested message and enum types in `ReserveInventoryRequest`.
pub mod reserve_inventory_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Identifier {
        #[prost(int64, tag = "1")]
        InventoryItemId(i64),
        #[prost(string, tag = "2")]
        ItemNumber(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReserveInventoryResponse {
    #[prost(string, tag = "1")]
    pub reservation_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub location_balance: ::core::option::Option<InventoryLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReleaseReservationRequest {
    #[prost(int32, tag = "3")]
    pub location_id: i32,
    /// Using string for Decimal precision
    #[prost(string, tag = "4")]
    pub quantity: ::prost::alloc::string::String,
    #[prost(oneof = "release_reservation_request::Identifier", tags = "1, 2")]
    pub identifier: ::core::option::Option<release_reservation_request::Identifier>,
}
/// Nested message and enum types in `ReleaseReservationRequest`.
pub mod release_reservation_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Identifier {
        #[prost(int64, tag = "1")]
        InventoryItemId(i64),
        #[prost(string, tag = "2")]
        ItemNumber(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReleaseReservationResponse {
    #[prost(message, optional, tag = "1")]
    pub location_balance: ::core::option::Option<InventoryLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInventoryRequest {
    #[prost(oneof = "get_inventory_request::Identifier", tags = "1, 2")]
    pub identifier: ::core::option::Option<get_inventory_request::Identifier>,
}
/// Nested message and enum types in `GetInventoryRequest`.
pub mod get_inventory_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Identifier {
        #[prost(int64, tag = "1")]
        InventoryItemId(i64),
        #[prost(string, tag = "2")]
        ItemNumber(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInventoryResponse {
    #[prost(message, optional, tag = "1")]
    pub item: ::core::option::Option<InventoryItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInventoryRequest {
    #[prost(uint64, tag = "1")]
    pub page: u64,
    #[prost(uint64, tag = "2")]
    pub limit: u64,
    #[prost(string, tag = "3")]
    pub product_filter: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub location_filter: i32,
    /// Using string for Decimal precision
    #[prost(string, tag = "5")]
    pub low_stock_threshold: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInventoryResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<InventoryItem>,
    #[prost(uint64, tag = "2")]
    pub total: u64,
    #[prost(uint64, tag = "3")]
    pub page: u64,
    #[prost(uint64, tag = "4")]
    pub per_page: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferInventoryRequest {
    #[prost(int64, tag = "1")]
    pub inventory_item_id: i64,
    #[prost(int32, tag = "2")]
    pub from_location_id: i32,
    #[prost(int32, tag = "3")]
    pub to_location_id: i32,
    /// Using string for Decimal precision
    #[prost(string, tag = "4")]
    pub quantity: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransferInventoryResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// Generated client implementations.
pub mod inventory_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct InventoryServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl InventoryServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> InventoryServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InventoryServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            InventoryServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn adjust_inventory(
            &mut self,
            request: impl tonic::IntoRequest<super::AdjustInventoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AdjustInventoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.inventory.InventoryService/AdjustInventory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.inventory.InventoryService",
                        "AdjustInventory",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn reserve_inventory(
            &mut self,
            request: impl tonic::IntoRequest<super::ReserveInventoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReserveInventoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.inventory.InventoryService/ReserveInventory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.inventory.InventoryService",
                        "ReserveInventory",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn release_reservation(
            &mut self,
            request: impl tonic::IntoRequest<super::ReleaseReservationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReleaseReservationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.inventory.InventoryService/ReleaseReservation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.inventory.InventoryService",
                        "ReleaseReservation",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_inventory(
            &mut self,
            request: impl tonic::IntoRequest<super::GetInventoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInventoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.inventory.InventoryService/GetInventory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.inventory.InventoryService",
                        "GetInventory",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_inventory(
            &mut self,
            request: impl tonic::IntoRequest<super::ListInventoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListInventoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.inventory.InventoryService/ListInventory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.inventory.InventoryService",
                        "ListInventory",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn transfer_inventory(
            &mut self,
            request: impl tonic::IntoRequest<super::TransferInventoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransferInventoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.inventory.InventoryService/TransferInventory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.inventory.InventoryService",
                        "TransferInventory",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
