// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Shipment {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub carrier: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tracking_number: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub shipping_address: ::core::option::Option<super::common::Address>,
    #[prost(string, tag = "6")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "9")]
    pub items: ::prost::alloc::vec::Vec<ShipmentItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShipmentItem {
    #[prost(string, tag = "1")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateShipmentRequest {
    #[prost(message, optional, tag = "1")]
    pub shipment: ::core::option::Option<Shipment>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateShipmentResponse {
    #[prost(string, tag = "1")]
    pub shipment_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetShipmentRequest {
    #[prost(string, tag = "1")]
    pub shipment_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetShipmentResponse {
    #[prost(message, optional, tag = "1")]
    pub shipment: ::core::option::Option<Shipment>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateShipmentStatusRequest {
    #[prost(string, tag = "1")]
    pub shipment_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateShipmentStatusResponse {
    #[prost(string, tag = "1")]
    pub shipment_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListShipmentsRequest {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub start_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "4")]
    pub end_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub pagination: ::core::option::Option<super::common::PaginationRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListShipmentsResponse {
    #[prost(message, repeated, tag = "1")]
    pub shipments: ::prost::alloc::vec::Vec<Shipment>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::PaginationResponse>,
}
/// Generated client implementations.
pub mod shipment_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ShipmentServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ShipmentServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ShipmentServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ShipmentServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ShipmentServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_shipment(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateShipmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateShipmentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.shipment.ShipmentService/CreateShipment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.shipment.ShipmentService",
                        "CreateShipment",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_shipment(
            &mut self,
            request: impl tonic::IntoRequest<super::GetShipmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetShipmentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.shipment.ShipmentService/GetShipment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("stateset.shipment.ShipmentService", "GetShipment"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_shipment_status(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateShipmentStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateShipmentStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.shipment.ShipmentService/UpdateShipmentStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.shipment.ShipmentService",
                        "UpdateShipmentStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_shipments(
            &mut self,
            request: impl tonic::IntoRequest<super::ListShipmentsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListShipmentsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.shipment.ShipmentService/ListShipments",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("stateset.shipment.ShipmentService", "ListShipments"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
