// This file is @generated by prost-build.
/// Represents a return request for an order.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Return {
    /// Unique identifier for the return
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Associated order ID
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    /// Associated customer ID
    #[prost(string, tag = "3")]
    pub customer_id: ::prost::alloc::string::String,
    /// List of items being returned
    #[prost(message, repeated, tag = "4")]
    pub items: ::prost::alloc::vec::Vec<ReturnItem>,
    /// Current status of the return
    #[prost(enumeration = "ReturnStatus", tag = "5")]
    pub status: i32,
    /// Reason for the return
    #[prost(string, tag = "6")]
    pub reason: ::prost::alloc::string::String,
    /// Timestamp when the return was created
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Timestamp when the return was last updated
    #[prost(message, optional, tag = "8")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Represents an item that is being returned.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReturnItem {
    /// Product ID of the item being returned
    #[prost(string, tag = "1")]
    pub product_id: ::prost::alloc::string::String,
    /// Quantity of the item being returned
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    /// Reason for returning this item
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
/// Request message for creating a return.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateReturnRequest {
    /// The return to be created
    #[prost(message, optional, tag = "1")]
    pub r#return: ::core::option::Option<Return>,
}
/// Response message for creating a return.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateReturnResponse {
    /// Unique identifier of the created return
    #[prost(string, tag = "1")]
    pub return_id: ::prost::alloc::string::String,
    /// Initial status of the created return
    #[prost(enumeration = "ReturnStatus", tag = "2")]
    pub status: i32,
}
/// Request message for retrieving a return.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReturnRequest {
    /// Unique identifier of the return to retrieve
    #[prost(string, tag = "1")]
    pub return_id: ::prost::alloc::string::String,
}
/// Response message for retrieving a return.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReturnResponse {
    /// The return data
    #[prost(message, optional, tag = "1")]
    pub r#return: ::core::option::Option<Return>,
}
/// Request message for updating a return's status.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateReturnStatusRequest {
    /// Unique identifier of the return
    #[prost(string, tag = "1")]
    pub return_id: ::prost::alloc::string::String,
    /// New status to be applied to the return
    #[prost(enumeration = "ReturnStatus", tag = "2")]
    pub new_status: i32,
}
/// Response message for updating a return's status.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateReturnStatusResponse {
    /// Unique identifier of the return
    #[prost(string, tag = "1")]
    pub return_id: ::prost::alloc::string::String,
    /// Updated status of the return
    #[prost(enumeration = "ReturnStatus", tag = "2")]
    pub status: i32,
}
/// Request message for listing returns.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListReturnsRequest {
    /// (Optional) Filter returns by customer ID
    #[prost(string, tag = "1")]
    pub customer_id: ::prost::alloc::string::String,
    /// (Optional) Filter returns by order ID
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    /// (Optional) Filter returns by status
    #[prost(enumeration = "ReturnStatus", tag = "3")]
    pub status: i32,
    /// (Optional) Start date for filtering returns
    #[prost(message, optional, tag = "4")]
    pub start_date: ::core::option::Option<::prost_types::Timestamp>,
    /// (Optional) End date for filtering returns
    #[prost(message, optional, tag = "5")]
    pub end_date: ::core::option::Option<::prost_types::Timestamp>,
    /// Pagination options
    #[prost(message, optional, tag = "6")]
    pub pagination: ::core::option::Option<super::common::PaginationRequest>,
}
/// Response message for listing returns.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListReturnsResponse {
    /// List of returns matching the request
    #[prost(message, repeated, tag = "1")]
    pub returns: ::prost::alloc::vec::Vec<Return>,
    /// Pagination information for the response
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::PaginationResponse>,
}
/// Enum representing the various statuses a return can have.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReturnStatus {
    /// Default status, used when the status is not known
    Unknown = 0,
    /// Return has been requested
    Requested = 1,
    /// Return has been approved
    Approved = 2,
    /// Return has been rejected
    Rejected = 3,
    /// Returned items have been received
    Received = 4,
    /// Return has been processed and refunded
    Refunded = 5,
}
impl ReturnStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Requested => "REQUESTED",
            Self::Approved => "APPROVED",
            Self::Rejected => "REJECTED",
            Self::Received => "RECEIVED",
            Self::Refunded => "REFUNDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "REQUESTED" => Some(Self::Requested),
            "APPROVED" => Some(Self::Approved),
            "REJECTED" => Some(Self::Rejected),
            "RECEIVED" => Some(Self::Received),
            "REFUNDED" => Some(Self::Refunded),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod return_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Return service definition.
    #[derive(Debug, Clone)]
    pub struct ReturnServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ReturnServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ReturnServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ReturnServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ReturnServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_return(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateReturnRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateReturnResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.return_order.ReturnService/CreateReturn",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.return_order.ReturnService",
                        "CreateReturn",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_return(
            &mut self,
            request: impl tonic::IntoRequest<super::GetReturnRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetReturnResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.return_order.ReturnService/GetReturn",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("stateset.return_order.ReturnService", "GetReturn"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_return_status(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateReturnStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateReturnStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.return_order.ReturnService/UpdateReturnStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.return_order.ReturnService",
                        "UpdateReturnStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_returns(
            &mut self,
            request: impl tonic::IntoRequest<super::ListReturnsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListReturnsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.return_order.ReturnService/ListReturns",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("stateset.return_order.ReturnService", "ListReturns"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
