// This file is @generated by prost-build.
/// Represents a monetary amount with a specific currency.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Money {
    /// ISO 4217 currency code (e.g., "USD", "EUR")
    #[prost(string, tag = "1")]
    pub currency: ::prost::alloc::string::String,
    /// Amount in the smallest units of the currency (e.g., cents for USD)
    #[prost(int64, tag = "2")]
    pub amount: i64,
}
/// Represents a physical address, including street, city, state, country, and postal code.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Address {
    /// First line of the street address
    #[prost(string, tag = "1")]
    pub street_line1: ::prost::alloc::string::String,
    /// Second line of the street address (optional)
    #[prost(string, tag = "2")]
    pub street_line2: ::prost::alloc::string::String,
    /// City of the address
    #[prost(string, tag = "3")]
    pub city: ::prost::alloc::string::String,
    /// State or province of the address
    #[prost(string, tag = "4")]
    pub state: ::prost::alloc::string::String,
    /// ISO 3166-1 alpha-2 country code (e.g., "US", "DE")
    #[prost(string, tag = "5")]
    pub country: ::prost::alloc::string::String,
    /// Postal code of the address
    #[prost(string, tag = "6")]
    pub postal_code: ::prost::alloc::string::String,
}
/// Request message for pagination, used in list queries to control the number of items returned.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PaginationRequest {
    /// The page number to retrieve (1-based index)
    #[prost(int32, tag = "1")]
    pub page: i32,
    /// The number of items per page
    #[prost(int32, tag = "2")]
    pub per_page: i32,
}
/// Response message for pagination, providing details about the current page and total number of items.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PaginationResponse {
    /// Total number of items available
    #[prost(int32, tag = "1")]
    pub total_items: i32,
    /// Total number of pages available
    #[prost(int32, tag = "2")]
    pub total_pages: i32,
    /// Current page number (1-based index)
    #[prost(int32, tag = "3")]
    pub current_page: i32,
    /// Number of items per page in the response
    #[prost(int32, tag = "4")]
    pub items_per_page: i32,
    /// Indicates if there is a next page
    #[prost(bool, tag = "5")]
    pub has_next_page: bool,
    /// Indicates if there is a previous page
    #[prost(bool, tag = "6")]
    pub has_previous_page: bool,
}
