// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Warranty {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub start_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub end_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "7")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub terms: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateWarrantyRequest {
    #[prost(message, optional, tag = "1")]
    pub warranty: ::core::option::Option<Warranty>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateWarrantyResponse {
    #[prost(string, tag = "1")]
    pub warranty_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWarrantyRequest {
    #[prost(string, tag = "1")]
    pub warranty_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWarrantyResponse {
    #[prost(message, optional, tag = "1")]
    pub warranty: ::core::option::Option<Warranty>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateWarrantyRequest {
    #[prost(message, optional, tag = "1")]
    pub warranty: ::core::option::Option<Warranty>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateWarrantyResponse {
    #[prost(message, optional, tag = "1")]
    pub warranty: ::core::option::Option<Warranty>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWarrantiesRequest {
    #[prost(string, tag = "1")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub pagination: ::core::option::Option<super::common::PaginationRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWarrantiesResponse {
    #[prost(message, repeated, tag = "1")]
    pub warranties: ::prost::alloc::vec::Vec<Warranty>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::PaginationResponse>,
}
/// Generated client implementations.
pub mod warranty_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct WarrantyServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl WarrantyServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> WarrantyServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> WarrantyServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            WarrantyServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_warranty(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateWarrantyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateWarrantyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.warranty.WarrantyService/CreateWarranty",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.warranty.WarrantyService",
                        "CreateWarranty",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_warranty(
            &mut self,
            request: impl tonic::IntoRequest<super::GetWarrantyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetWarrantyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.warranty.WarrantyService/GetWarranty",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("stateset.warranty.WarrantyService", "GetWarranty"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_warranty(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateWarrantyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateWarrantyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.warranty.WarrantyService/UpdateWarranty",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.warranty.WarrantyService",
                        "UpdateWarranty",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_warranties(
            &mut self,
            request: impl tonic::IntoRequest<super::ListWarrantiesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListWarrantiesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.warranty.WarrantyService/ListWarranties",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.warranty.WarrantyService",
                        "ListWarranties",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
