// This file is @generated by prost-build.
/// Represents a purchase order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PurchaseOrder {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub po_number: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub supplier_id: ::prost::alloc::string::String,
    #[prost(enumeration = "PurchaseOrderStatus", tag = "4")]
    pub status: i32,
    #[prost(message, optional, tag = "5")]
    pub order_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub expected_delivery_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub total_amount: ::core::option::Option<super::common::Money>,
    #[prost(string, tag = "8")]
    pub currency: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub notes: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub approved_by: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "12")]
    pub approved_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "13")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "14")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "15")]
    pub items: ::prost::alloc::vec::Vec<PurchaseOrderItem>,
}
/// Represents an item within a purchase order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PurchaseOrderItem {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sku: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub product_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub description: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub quantity_ordered: i32,
    #[prost(int32, tag = "7")]
    pub quantity_received: i32,
    #[prost(message, optional, tag = "8")]
    pub unit_cost: ::core::option::Option<super::common::Money>,
    #[prost(message, optional, tag = "9")]
    pub total_cost: ::core::option::Option<super::common::Money>,
    #[prost(string, tag = "10")]
    pub notes: ::prost::alloc::string::String,
}
/// Create
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePurchaseOrderRequest {
    #[prost(string, tag = "1")]
    pub supplier_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub expected_delivery_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<CreatePurchaseOrderItem>,
    #[prost(message, optional, tag = "4")]
    pub shipping_address: ::core::option::Option<super::common::Address>,
    #[prost(string, tag = "5")]
    pub notes: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub payment_terms: ::prost::alloc::string::String,
    /// ISO 4217
    #[prost(string, tag = "7")]
    pub currency: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePurchaseOrderItem {
    #[prost(string, tag = "1")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    #[prost(message, optional, tag = "3")]
    pub unit_price: ::core::option::Option<super::common::Money>,
    #[prost(double, tag = "4")]
    pub tax_rate: f64,
    /// ISO 4217 (optional override)
    #[prost(string, tag = "5")]
    pub currency: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePurchaseOrderResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// Get by ID
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPurchaseOrderRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPurchaseOrderResponse {
    #[prost(message, optional, tag = "1")]
    pub purchase_order: ::core::option::Option<PurchaseOrder>,
}
/// Update
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePurchaseOrderRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub expected_delivery_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub shipping_address: ::core::option::Option<super::common::Address>,
    #[prost(string, tag = "4")]
    pub notes: ::prost::alloc::string::String,
    #[prost(enumeration = "PurchaseOrderStatus", tag = "5")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePurchaseOrderResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// Approve
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApprovePurchaseOrderRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub approver_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub notes: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApprovePurchaseOrderResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// Cancel
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelPurchaseOrderRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelPurchaseOrderResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// Receive
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceivePurchaseOrderRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub received_by: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub notes: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub items_received: ::prost::alloc::vec::Vec<ReceivedItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceivedItem {
    #[prost(string, tag = "1")]
    pub line_item_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity_received: i32,
    #[prost(string, tag = "3")]
    pub condition: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceivePurchaseOrderResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// List/Filter
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPurchaseOrdersRequest {
    #[prost(string, tag = "1")]
    pub supplier_id: ::prost::alloc::string::String,
    #[prost(enumeration = "PurchaseOrderStatus", tag = "2")]
    pub status: i32,
    /// created_at >=
    #[prost(message, optional, tag = "3")]
    pub start_date: ::core::option::Option<::prost_types::Timestamp>,
    /// created_at <=
    #[prost(message, optional, tag = "4")]
    pub end_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub pagination: ::core::option::Option<super::common::PaginationRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPurchaseOrdersResponse {
    #[prost(message, repeated, tag = "1")]
    pub purchase_orders: ::prost::alloc::vec::Vec<PurchaseOrder>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::PaginationResponse>,
}
/// Purchase order statuses aligning with the model
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PurchaseOrderStatus {
    PoStatusUnspecified = 0,
    PoStatusDraft = 1,
    PoStatusSubmitted = 2,
    PoStatusApproved = 3,
    PoStatusRejected = 4,
    PoStatusOrdered = 5,
    PoStatusPartiallyReceived = 6,
    PoStatusReceived = 7,
    PoStatusCancelled = 8,
}
impl PurchaseOrderStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PoStatusUnspecified => "PO_STATUS_UNSPECIFIED",
            Self::PoStatusDraft => "PO_STATUS_DRAFT",
            Self::PoStatusSubmitted => "PO_STATUS_SUBMITTED",
            Self::PoStatusApproved => "PO_STATUS_APPROVED",
            Self::PoStatusRejected => "PO_STATUS_REJECTED",
            Self::PoStatusOrdered => "PO_STATUS_ORDERED",
            Self::PoStatusPartiallyReceived => "PO_STATUS_PARTIALLY_RECEIVED",
            Self::PoStatusReceived => "PO_STATUS_RECEIVED",
            Self::PoStatusCancelled => "PO_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PO_STATUS_UNSPECIFIED" => Some(Self::PoStatusUnspecified),
            "PO_STATUS_DRAFT" => Some(Self::PoStatusDraft),
            "PO_STATUS_SUBMITTED" => Some(Self::PoStatusSubmitted),
            "PO_STATUS_APPROVED" => Some(Self::PoStatusApproved),
            "PO_STATUS_REJECTED" => Some(Self::PoStatusRejected),
            "PO_STATUS_ORDERED" => Some(Self::PoStatusOrdered),
            "PO_STATUS_PARTIALLY_RECEIVED" => Some(Self::PoStatusPartiallyReceived),
            "PO_STATUS_RECEIVED" => Some(Self::PoStatusReceived),
            "PO_STATUS_CANCELLED" => Some(Self::PoStatusCancelled),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod purchase_order_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PurchaseOrderServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PurchaseOrderServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PurchaseOrderServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PurchaseOrderServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PurchaseOrderServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_purchase_order(
            &mut self,
            request: impl tonic::IntoRequest<super::CreatePurchaseOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreatePurchaseOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.purchase_order.PurchaseOrderService/CreatePurchaseOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.purchase_order.PurchaseOrderService",
                        "CreatePurchaseOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_purchase_order(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPurchaseOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPurchaseOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.purchase_order.PurchaseOrderService/GetPurchaseOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.purchase_order.PurchaseOrderService",
                        "GetPurchaseOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_purchase_order(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdatePurchaseOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdatePurchaseOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.purchase_order.PurchaseOrderService/UpdatePurchaseOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.purchase_order.PurchaseOrderService",
                        "UpdatePurchaseOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn approve_purchase_order(
            &mut self,
            request: impl tonic::IntoRequest<super::ApprovePurchaseOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ApprovePurchaseOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.purchase_order.PurchaseOrderService/ApprovePurchaseOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.purchase_order.PurchaseOrderService",
                        "ApprovePurchaseOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_purchase_order(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelPurchaseOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelPurchaseOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.purchase_order.PurchaseOrderService/CancelPurchaseOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.purchase_order.PurchaseOrderService",
                        "CancelPurchaseOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn receive_purchase_order(
            &mut self,
            request: impl tonic::IntoRequest<super::ReceivePurchaseOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReceivePurchaseOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.purchase_order.PurchaseOrderService/ReceivePurchaseOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.purchase_order.PurchaseOrderService",
                        "ReceivePurchaseOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_purchase_orders(
            &mut self,
            request: impl tonic::IntoRequest<super::ListPurchaseOrdersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListPurchaseOrdersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.purchase_order.PurchaseOrderService/ListPurchaseOrders",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.purchase_order.PurchaseOrderService",
                        "ListPurchaseOrders",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
