// This file is @generated by prost-build.
/// The Order message represents a customer's order.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Order {
    /// Unique identifier for the order
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Unique identifier for the customer
    #[prost(string, tag = "2")]
    pub customer_id: ::prost::alloc::string::String,
    /// List of items in the order
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<OrderItem>,
    /// Total amount for the order
    #[prost(message, optional, tag = "4")]
    pub total_amount: ::core::option::Option<super::common::Money>,
    /// Status of the order, default is PENDING
    #[prost(enumeration = "OrderStatus", tag = "5")]
    pub status: i32,
    /// Timestamp when the order was created
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Shipping address for the order
    #[prost(message, optional, tag = "7")]
    pub shipping_address: ::core::option::Option<super::common::Address>,
    /// Billing address for the order
    #[prost(message, optional, tag = "8")]
    pub billing_address: ::core::option::Option<super::common::Address>,
    /// Payment method used for the order
    #[prost(string, tag = "9")]
    pub payment_method_id: ::prost::alloc::string::String,
    /// Shipment identifier for the order
    #[prost(string, tag = "10")]
    pub shipment_id: ::prost::alloc::string::String,
}
/// The OrderItem message represents an item in an order.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderItem {
    /// Unique identifier for the product
    #[prost(string, tag = "1")]
    pub product_id: ::prost::alloc::string::String,
    /// Quantity of the product ordered, default is 1
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    /// Unit price of the product
    #[prost(message, optional, tag = "3")]
    pub unit_price: ::core::option::Option<super::common::Money>,
}
/// Request message for creating an order.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrderRequest {
    /// The order to be created
    #[prost(message, optional, tag = "1")]
    pub order: ::core::option::Option<Order>,
}
/// Response message for creating an order.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrderResponse {
    /// The unique identifier of the created order
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    /// The initial status of the created order
    #[prost(enumeration = "OrderStatus", tag = "2")]
    pub status: i32,
    /// Timestamp when the order was created
    #[prost(message, optional, tag = "3")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Request message for retrieving an order.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrderRequest {
    /// The unique identifier of the order to retrieve
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
}
/// Response message for retrieving an order.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrderResponse {
    /// The order data
    #[prost(message, optional, tag = "1")]
    pub order: ::core::option::Option<Order>,
}
/// Request message for updating an order's status.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateOrderStatusRequest {
    /// The unique identifier of the order
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    /// The new status to be applied to the order
    #[prost(enumeration = "OrderStatus", tag = "2")]
    pub new_status: i32,
}
/// Response message for updating an order's status.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateOrderStatusResponse {
    /// The unique identifier of the order
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    /// The updated status of the order
    #[prost(enumeration = "OrderStatus", tag = "2")]
    pub status: i32,
}
/// Request message for listing orders.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrdersRequest {
    /// (Optional) Filter orders by customer ID
    #[prost(string, tag = "1")]
    pub customer_id: ::prost::alloc::string::String,
    /// (Optional) Start date for filtering orders
    #[prost(message, optional, tag = "2")]
    pub start_date: ::core::option::Option<::prost_types::Timestamp>,
    /// (Optional) End date for filtering orders
    #[prost(message, optional, tag = "3")]
    pub end_date: ::core::option::Option<::prost_types::Timestamp>,
    /// (Optional) Filter orders by status
    #[prost(enumeration = "OrderStatus", tag = "4")]
    pub status: i32,
    /// Pagination options
    #[prost(message, optional, tag = "5")]
    pub pagination: ::core::option::Option<super::common::PaginationRequest>,
}
/// Response message for listing orders.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrdersResponse {
    /// List of orders matching the request
    #[prost(message, repeated, tag = "1")]
    pub orders: ::prost::alloc::vec::Vec<Order>,
    /// Pagination information for the response
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::PaginationResponse>,
}
/// Enum representing the various statuses an order can have.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderStatus {
    /// Default status, used when the status is not known
    Unknown = 0,
    /// Order is pending and has not been processed yet
    Pending = 1,
    /// Order is being processed
    Processing = 2,
    /// Order has been shipped
    Shipped = 3,
    /// Order has been delivered to the customer
    Delivered = 4,
    /// Order has been canceled
    Canceled = 5,
    /// Order has been returned
    Returned = 6,
}
impl OrderStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Pending => "PENDING",
            Self::Processing => "PROCESSING",
            Self::Shipped => "SHIPPED",
            Self::Delivered => "DELIVERED",
            Self::Canceled => "CANCELED",
            Self::Returned => "RETURNED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "PENDING" => Some(Self::Pending),
            "PROCESSING" => Some(Self::Processing),
            "SHIPPED" => Some(Self::Shipped),
            "DELIVERED" => Some(Self::Delivered),
            "CANCELED" => Some(Self::Canceled),
            "RETURNED" => Some(Self::Returned),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod order_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Order service definition.
    #[derive(Debug, Clone)]
    pub struct OrderServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl OrderServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> OrderServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> OrderServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            OrderServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_order(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.order.OrderService/CreateOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("stateset.order.OrderService", "CreateOrder"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_order(
            &mut self,
            request: impl tonic::IntoRequest<super::GetOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.order.OrderService/GetOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("stateset.order.OrderService", "GetOrder"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_order_status(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateOrderStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateOrderStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.order.OrderService/UpdateOrderStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("stateset.order.OrderService", "UpdateOrderStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_orders(
            &mut self,
            request: impl tonic::IntoRequest<super::ListOrdersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListOrdersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.order.OrderService/ListOrders",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("stateset.order.OrderService", "ListOrders"));
            self.inner.unary(req, path, codec).await
        }
    }
}
