// This file is @generated by prost-build.
/// WorkOrder represents a task or job to be completed
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkOrder {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "WorkOrderStatus", tag = "4")]
    pub status: i32,
    #[prost(enumeration = "WorkOrderPriority", tag = "5")]
    pub priority: i32,
    #[prost(int32, tag = "6")]
    pub assigned_to: i32,
    #[prost(int32, tag = "7")]
    pub product_id: i32,
    #[prost(int32, tag = "8")]
    pub quantity: i32,
    #[prost(message, optional, tag = "9")]
    pub due_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// CreateWorkOrderRequest is used to create a new work order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateWorkOrderRequest {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "WorkOrderPriority", tag = "3")]
    pub priority: i32,
    #[prost(int32, tag = "4")]
    pub assigned_to: i32,
    #[prost(int32, tag = "5")]
    pub product_id: i32,
    #[prost(int32, tag = "6")]
    pub quantity: i32,
    #[prost(message, optional, tag = "7")]
    pub due_date: ::core::option::Option<::prost_types::Timestamp>,
}
/// CreateWorkOrderResponse is the response for creating a work order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateWorkOrderResponse {
    #[prost(message, optional, tag = "1")]
    pub work_order: ::core::option::Option<WorkOrder>,
}
/// GetWorkOrderRequest is used to retrieve a specific work order
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetWorkOrderRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
/// GetWorkOrderResponse is the response for retrieving a work order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWorkOrderResponse {
    #[prost(message, optional, tag = "1")]
    pub work_order: ::core::option::Option<WorkOrder>,
}
/// UpdateWorkOrderRequest is used to update an existing work order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateWorkOrderRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "WorkOrderStatus", tag = "4")]
    pub status: i32,
    #[prost(enumeration = "WorkOrderPriority", tag = "5")]
    pub priority: i32,
    #[prost(int32, tag = "6")]
    pub assigned_to: i32,
    #[prost(int32, tag = "7")]
    pub quantity: i32,
    #[prost(message, optional, tag = "8")]
    pub due_date: ::core::option::Option<::prost_types::Timestamp>,
}
/// UpdateWorkOrderResponse is the response for updating a work order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateWorkOrderResponse {
    #[prost(message, optional, tag = "1")]
    pub work_order: ::core::option::Option<WorkOrder>,
}
/// DeleteWorkOrderRequest is used to delete a work order
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteWorkOrderRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
/// DeleteWorkOrderResponse is the response for deleting a work order
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteWorkOrderResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// ListWorkOrdersRequest is used to retrieve a list of work orders
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListWorkOrdersRequest {
    #[prost(enumeration = "WorkOrderStatus", tag = "1")]
    pub status: i32,
    #[prost(enumeration = "WorkOrderPriority", tag = "2")]
    pub priority: i32,
    #[prost(int32, tag = "3")]
    pub assigned_to: i32,
    #[prost(message, optional, tag = "4")]
    pub pagination: ::core::option::Option<super::common::PaginationRequest>,
}
/// ListWorkOrdersResponse is the response for listing work orders
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWorkOrdersResponse {
    #[prost(message, repeated, tag = "1")]
    pub work_orders: ::prost::alloc::vec::Vec<WorkOrder>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::PaginationResponse>,
}
/// AssignWorkOrderRequest is used to assign a work order to a user
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AssignWorkOrderRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub user_id: i32,
}
/// AssignWorkOrderResponse is the response for assigning a work order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssignWorkOrderResponse {
    #[prost(message, optional, tag = "1")]
    pub work_order: ::core::option::Option<WorkOrder>,
}
/// CompleteWorkOrderRequest is used to mark a work order as completed
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CompleteWorkOrderRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
/// CompleteWorkOrderResponse is the response for completing a work order
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompleteWorkOrderResponse {
    #[prost(message, optional, tag = "1")]
    pub work_order: ::core::option::Option<WorkOrder>,
}
/// WorkOrderStatus represents the current state of a work order
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WorkOrderStatus {
    Unspecified = 0,
    Pending = 1,
    InProgress = 2,
    Completed = 3,
    Cancelled = 4,
}
impl WorkOrderStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WORK_ORDER_STATUS_UNSPECIFIED",
            Self::Pending => "WORK_ORDER_STATUS_PENDING",
            Self::InProgress => "WORK_ORDER_STATUS_IN_PROGRESS",
            Self::Completed => "WORK_ORDER_STATUS_COMPLETED",
            Self::Cancelled => "WORK_ORDER_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WORK_ORDER_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "WORK_ORDER_STATUS_PENDING" => Some(Self::Pending),
            "WORK_ORDER_STATUS_IN_PROGRESS" => Some(Self::InProgress),
            "WORK_ORDER_STATUS_COMPLETED" => Some(Self::Completed),
            "WORK_ORDER_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
/// WorkOrderPriority represents the urgency of a work order
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WorkOrderPriority {
    Unspecified = 0,
    Low = 1,
    Medium = 2,
    High = 3,
    Urgent = 4,
}
impl WorkOrderPriority {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WORK_ORDER_PRIORITY_UNSPECIFIED",
            Self::Low => "WORK_ORDER_PRIORITY_LOW",
            Self::Medium => "WORK_ORDER_PRIORITY_MEDIUM",
            Self::High => "WORK_ORDER_PRIORITY_HIGH",
            Self::Urgent => "WORK_ORDER_PRIORITY_URGENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WORK_ORDER_PRIORITY_UNSPECIFIED" => Some(Self::Unspecified),
            "WORK_ORDER_PRIORITY_LOW" => Some(Self::Low),
            "WORK_ORDER_PRIORITY_MEDIUM" => Some(Self::Medium),
            "WORK_ORDER_PRIORITY_HIGH" => Some(Self::High),
            "WORK_ORDER_PRIORITY_URGENT" => Some(Self::Urgent),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod work_order_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// WorkOrderService defines the gRPC service for managing work orders
    #[derive(Debug, Clone)]
    pub struct WorkOrderServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl WorkOrderServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> WorkOrderServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> WorkOrderServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            WorkOrderServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_work_order(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateWorkOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateWorkOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.work_order.WorkOrderService/CreateWorkOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.work_order.WorkOrderService",
                        "CreateWorkOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_work_order(
            &mut self,
            request: impl tonic::IntoRequest<super::GetWorkOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetWorkOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.work_order.WorkOrderService/GetWorkOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.work_order.WorkOrderService",
                        "GetWorkOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_work_order(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateWorkOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateWorkOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.work_order.WorkOrderService/UpdateWorkOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.work_order.WorkOrderService",
                        "UpdateWorkOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_work_order(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteWorkOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteWorkOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.work_order.WorkOrderService/DeleteWorkOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.work_order.WorkOrderService",
                        "DeleteWorkOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_work_orders(
            &mut self,
            request: impl tonic::IntoRequest<super::ListWorkOrdersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListWorkOrdersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.work_order.WorkOrderService/ListWorkOrders",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.work_order.WorkOrderService",
                        "ListWorkOrders",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn assign_work_order(
            &mut self,
            request: impl tonic::IntoRequest<super::AssignWorkOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AssignWorkOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.work_order.WorkOrderService/AssignWorkOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.work_order.WorkOrderService",
                        "AssignWorkOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn complete_work_order(
            &mut self,
            request: impl tonic::IntoRequest<super::CompleteWorkOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CompleteWorkOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.work_order.WorkOrderService/CompleteWorkOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.work_order.WorkOrderService",
                        "CompleteWorkOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
