"""Stub file for torch module (optional dependency)."""

from typing import Any, Iterator, Optional, Tuple, Union

class dtype: ...

float16: dtype
float32: dtype
bfloat16: dtype

class Tensor:
    device: Any
    def to(self, device: Any) -> "Tensor": ...
    def tolist(self) -> list: ...
    def detach(self) -> "Tensor": ...
    def cpu(self) -> "Tensor": ...
    def numpy(self) -> Any: ...
    @property
    def shape(self) -> Tuple[int, ...]: ...
    def __getitem__(self, key: Any) -> "Tensor": ...

class device:
    def __init__(self, name: str) -> None: ...

class cuda:
    @staticmethod
    def is_available() -> bool: ...
    @staticmethod
    def is_bf16_supported() -> bool: ...
    @staticmethod
    def device_count() -> int: ...
    @staticmethod
    def get_device_name(device: int = 0) -> str: ...

def no_grad() -> Any: ...
def tensor(data: Any, requires_grad: bool = False) -> Tensor: ...
def randn(*size: int, requires_grad: bool = False) -> Tensor: ...
