"""Lazy-export registry for :mod:`stateset_agents.training`.

Maps public attribute names to the ``(module, attribute)`` pair that provides
them.  Kept in a separate module so that ``__init__`` stays small; the mapping
is data only and must not import anything heavy.
"""

_PKG = __name__.rpartition(".")[0]

OPTIONAL_EXPORTS: dict[str, tuple[str, str]] = {
    # Core training surface (lazy so that importing this package stays
    # torch-free; every one of these modules imports torch transitively).
    "TrainingConfig": (f"{_PKG}.config", "TrainingConfig"),
    "TrainingProfile": (f"{_PKG}.config", "TrainingProfile"),
    "get_config_for_task": (f"{_PKG}.config", "get_config_for_task"),
    "ContinualLearningConfig": (
        f"{_PKG}.continual_learning",
        "ContinualLearningConfig",
    ),
    "ContinualLearningManager": (
        f"{_PKG}.continual_learning",
        "ContinualLearningManager",
    ),
    "TrajectoryReplayBuffer": (
        f"{_PKG}.continual_learning",
        "TrajectoryReplayBuffer",
    ),
    "EvaluationConfig": (f"{_PKG}.evaluation", "EvaluationConfig"),
    "evaluate_agent": (f"{_PKG}.evaluation", "evaluate_agent"),
    "TrainingMode": (f"{_PKG}.train", "TrainingMode"),
    "train": (f"{_PKG}.train", "train"),
    "GRPOTrainer": (f"{_PKG}.trainer", "GRPOTrainer"),
    "MultiTurnGRPOTrainer": (f"{_PKG}.trainer", "MultiTurnGRPOTrainer"),
    "SingleTurnGRPOTrainer": (f"{_PKG}.trainer", "SingleTurnGRPOTrainer"),
    # Framework-neutral training-engine contract (lightweight, lazy for a
    # uniform public export policy).
    "BACKEND_PROTOCOL": (f"{_PKG}.backends", "BACKEND_PROTOCOL"),
    "BACKEND_PROTOCOL_VERSION": (
        f"{_PKG}.backends",
        "BACKEND_PROTOCOL_VERSION",
    ),
    "BackendCapabilities": (f"{_PKG}.backends", "BackendCapabilities"),
    "BackendError": (f"{_PKG}.backends", "BackendError"),
    "BackendExecutionError": (f"{_PKG}.backends", "BackendExecutionError"),
    "BackendRegistry": (f"{_PKG}.backends", "BackendRegistry"),
    "BackendResult": (f"{_PKG}.backends", "BackendResult"),
    "CommandTrainingBackend": (f"{_PKG}.backends", "CommandTrainingBackend"),
    "TrainingBackend": (f"{_PKG}.backends", "TrainingBackend"),
    "TrainingExperiment": (f"{_PKG}.backends", "TrainingExperiment"),
    # Native policy-versioned asynchronous rollout control plane.
    "AsyncRolloutClosed": (
        f"{_PKG}.async_rollouts",
        "AsyncRolloutClosed",
    ),
    "AsyncRolloutConfig": (
        f"{_PKG}.async_rollouts",
        "AsyncRolloutConfig",
    ),
    "AsyncRolloutCoordinator": (
        f"{_PKG}.async_rollouts",
        "AsyncRolloutCoordinator",
    ),
    "AsyncRolloutError": (
        f"{_PKG}.async_rollouts",
        "AsyncRolloutError",
    ),
    "AsyncRolloutStats": (
        f"{_PKG}.async_rollouts",
        "AsyncRolloutStats",
    ),
    "AsyncRolloutTimeout": (
        f"{_PKG}.async_rollouts",
        "AsyncRolloutTimeout",
    ),
    "RolloutBatch": (f"{_PKG}.async_rollouts", "RolloutBatch"),
    "RolloutRecord": (f"{_PKG}.async_rollouts", "RolloutRecord"),
    "compute_importance_weights": (
        f"{_PKG}.async_rollouts",
        "compute_importance_weights",
    ),
    "AsyncRolloutRunResult": (
        f"{_PKG}.async_runtime",
        "AsyncRolloutRunResult",
    ),
    "AsyncRolloutRuntime": (
        f"{_PKG}.async_runtime",
        "AsyncRolloutRuntime",
    ),
    "AsyncRolloutRuntimeConfig": (
        f"{_PKG}.async_runtime",
        "AsyncRolloutRuntimeConfig",
    ),
    "AsyncRolloutWorkerError": (
        f"{_PKG}.async_runtime",
        "AsyncRolloutWorkerError",
    ),
    "LearnerStep": (f"{_PKG}.async_runtime", "LearnerStep"),
    "PolicyPublisher": (f"{_PKG}.async_runtime", "PolicyPublisher"),
    "RolloutProducer": (f"{_PKG}.async_runtime", "RolloutProducer"),
    "DistributedRolloutConfig": (
        f"{_PKG}.distributed_rollouts",
        "DistributedRolloutConfig",
    ),
    "DistributedRolloutControlPlane": (
        f"{_PKG}.distributed_rollouts",
        "DistributedRolloutControlPlane",
    ),
    "DistributedRolloutStats": (
        f"{_PKG}.distributed_rollouts",
        "DistributedRolloutStats",
    ),
    "WorkerCapacityError": (
        f"{_PKG}.distributed_rollouts",
        "WorkerCapacityError",
    ),
    "WorkerHealth": (f"{_PKG}.distributed_rollouts", "WorkerHealth"),
    "WorkerLease": (f"{_PKG}.distributed_rollouts", "WorkerLease"),
    "WorkerLeaseError": (
        f"{_PKG}.distributed_rollouts",
        "WorkerLeaseError",
    ),
    "WorkerLeaseExpired": (
        f"{_PKG}.distributed_rollouts",
        "WorkerLeaseExpired",
    ),
    "PolicyArtifact": (f"{_PKG}.policy_artifacts", "PolicyArtifact"),
    "PolicyArtifactError": (
        f"{_PKG}.policy_artifacts",
        "PolicyArtifactError",
    ),
    "PolicyArtifactUnavailable": (
        f"{_PKG}.policy_artifacts",
        "PolicyArtifactUnavailable",
    ),
    "compute_policy_artifact_sha256": (
        f"{_PKG}.policy_artifacts",
        "compute_policy_artifact_sha256",
    ),
    "verify_policy_artifact": (
        f"{_PKG}.policy_artifacts",
        "verify_policy_artifact",
    ),
    "OpenRLHFConfigError": (
        f"{_PKG}.adapters.openrlhf",
        "OpenRLHFConfigError",
    ),
    "build_openrlhf_command": (
        f"{_PKG}.adapters.openrlhf",
        "build_openrlhf_command",
    ),
    "openrlhf_backend": (f"{_PKG}.adapters.openrlhf", "openrlhf_backend"),
    "VerlConfigError": (f"{_PKG}.adapters.verl", "VerlConfigError"),
    "build_verl_command": (f"{_PKG}.adapters.verl", "build_verl_command"),
    "verl_backend": (f"{_PKG}.adapters.verl", "verl_backend"),
    "NemoRLConfigError": (
        f"{_PKG}.adapters.nemo_rl",
        "NemoRLConfigError",
    ),
    "build_nemo_rl_command": (
        f"{_PKG}.adapters.nemo_rl",
        "build_nemo_rl_command",
    ),
    "nemo_rl_backend": (f"{_PKG}.adapters.nemo_rl", "nemo_rl_backend"),
    # Auto-Research Loop
    "AutoResearchConfig": (f"{_PKG}.auto_research.config", "AutoResearchConfig"),
    "AutoResearchLoop": (
        f"{_PKG}.auto_research.experiment_loop",
        "AutoResearchLoop",
    ),
    "run_auto_research": (
        f"{_PKG}.auto_research.experiment_loop",
        "run_auto_research",
    ),
    "ExperimentTracker": (
        f"{_PKG}.auto_research.experiment_tracker",
        "ExperimentTracker",
    ),
    "ExperimentRecord": (
        f"{_PKG}.auto_research.experiment_tracker",
        "ExperimentRecord",
    ),
    "CheckpointManager": (
        f"{_PKG}.auto_research.checkpoint_manager",
        "CheckpointManager",
    ),
    "ExperimentProposer": (f"{_PKG}.auto_research.proposer", "ExperimentProposer"),
    "RandomProposer": (f"{_PKG}.auto_research.proposer", "RandomProposer"),
    "PerturbationProposer": (
        f"{_PKG}.auto_research.proposer",
        "PerturbationProposer",
    ),
    "GridProposer": (f"{_PKG}.auto_research.proposer", "GridProposer"),
    "BayesianProposer": (f"{_PKG}.auto_research.proposer", "BayesianProposer"),
    "LLMProposer": (f"{_PKG}.auto_research.llm_proposer", "LLMProposer"),
    "create_proposer": (f"{_PKG}.auto_research.proposer", "create_proposer"),
    "create_auto_research_search_space": (
        f"{_PKG}.auto_research.search_spaces",
        "create_auto_research_search_space",
    ),
    "create_quick_search_space": (
        f"{_PKG}.auto_research.search_spaces",
        "create_quick_search_space",
    ),
    "get_auto_research_search_space": (
        f"{_PKG}.auto_research.search_spaces",
        "get_auto_research_search_space",
    ),
    # TRL-based GRPO
    "ModelManager": (f"{_PKG}.trl_grpo_trainer", "ModelManager"),
    "TRLGRPOConfig": (f"{_PKG}.trl_grpo_config", "TRLGRPOConfig"),
    "TRLGRPODatasetBuilder": (f"{_PKG}.trl_grpo_trainer", "TRLGRPODatasetBuilder"),
    "TRLGRPORewardFunction": (f"{_PKG}.trl_grpo_trainer", "TRLGRPORewardFunction"),
    "TRLGRPOTrainerWrapper": (f"{_PKG}.trl_grpo_trainer", "TRLGRPOTrainerWrapper"),
    "train_with_trl_grpo": (f"{_PKG}.trl_grpo_entrypoints", "train_with_trl_grpo"),
    "train_customer_service_with_trl": (
        f"{_PKG}.trl_grpo_entrypoints",
        "train_customer_service_with_trl",
    ),
    # GSPO / GEPO / DAPO / VAPO
    "GSPOConfig": (f"{_PKG}.gspo_trainer", "GSPOConfig"),
    "GSPOTrainer": (f"{_PKG}.gspo_trainer", "GSPOTrainer"),
    "GSPO_Trainer": (f"{_PKG}.gspo_trainer", "GSPO_Trainer"),
    "train_with_gspo": (f"{_PKG}.gspo_trainer", "train_with_gspo"),
    # Qwen3.5 starter path
    "QWEN35_08B_BASE_MODEL": (f"{_PKG}.qwen3_5_starter", "QWEN35_08B_BASE_MODEL"),
    "QWEN35_08B_CONFIG_SUFFIXES": (
        f"{_PKG}.qwen3_5_starter",
        "QWEN35_08B_CONFIG_SUFFIXES",
    ),
    "QWEN35_08B_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.qwen3_5_starter",
        "QWEN35_08B_DEFAULT_OUTPUT_DIR",
    ),
    "QWEN35_08B_LORA_TARGET_MODULES": (
        f"{_PKG}.qwen3_5_starter",
        "QWEN35_08B_LORA_TARGET_MODULES",
    ),
    "QWEN35_08B_POST_TRAINED_MODEL": (
        f"{_PKG}.qwen3_5_starter",
        "QWEN35_08B_POST_TRAINED_MODEL",
    ),
    "QWEN35_08B_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.qwen3_5_starter",
        "QWEN35_08B_STARTER_PROFILE_CHOICES",
    ),
    "QWEN35_08B_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.qwen3_5_starter",
        "QWEN35_08B_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "QWEN35_08B_SUPPORTED_VARIANTS": (
        f"{_PKG}.qwen3_5_starter",
        "QWEN35_08B_SUPPORTED_VARIANTS",
    ),
    "QWEN35_08B_TASK_CHOICES": (
        f"{_PKG}.qwen3_5_starter",
        "QWEN35_08B_TASK_CHOICES",
    ),
    "Qwen35Config": (f"{_PKG}.qwen3_5_starter", "Qwen35Config"),
    "create_qwen3_5_agent_config": (
        f"{_PKG}.qwen3_5_starter",
        "create_qwen3_5_agent_config",
    ),
    "create_qwen3_5_preview": (f"{_PKG}.qwen3_5_starter", "create_qwen3_5_preview"),
    "describe_qwen3_5_starter_profiles": (
        f"{_PKG}.qwen3_5_starter",
        "describe_qwen3_5_starter_profiles",
    ),
    "finetune_qwen3_5_0_8b": (f"{_PKG}.qwen3_5_starter", "finetune_qwen3_5_0_8b"),
    "get_qwen3_5_config": (f"{_PKG}.qwen3_5_starter", "get_qwen3_5_config"),
    "get_qwen3_5_gspo_config": (
        f"{_PKG}.qwen3_5_starter",
        "get_qwen3_5_gspo_config",
    ),
    "get_qwen3_5_gspo_overrides": (
        f"{_PKG}.qwen3_5_starter",
        "get_qwen3_5_gspo_overrides",
    ),
    "get_qwen3_5_profile_description": (
        f"{_PKG}.qwen3_5_starter",
        "get_qwen3_5_profile_description",
    ),
    "get_qwen3_5_profile_overrides": (
        f"{_PKG}.qwen3_5_starter",
        "get_qwen3_5_profile_overrides",
    ),
    "get_qwen3_5_system_prompt": (
        f"{_PKG}.qwen3_5_starter",
        "get_qwen3_5_system_prompt",
    ),
    "load_qwen3_5_config_file": (
        f"{_PKG}.qwen3_5_starter",
        "load_qwen3_5_config_file",
    ),
    "run_qwen3_5_0_8b_config": (
        f"{_PKG}.qwen3_5_starter",
        "run_qwen3_5_0_8b_config",
    ),
    "summarize_qwen3_5_config": (
        f"{_PKG}.qwen3_5_starter",
        "summarize_qwen3_5_config",
    ),
    "validate_qwen3_5_config": (
        f"{_PKG}.qwen3_5_starter",
        "validate_qwen3_5_config",
    ),
    "write_qwen3_5_config_file": (
        f"{_PKG}.qwen3_5_starter",
        "write_qwen3_5_config_file",
    ),
    # Kimi-K2.6 starter path
    "KIMI_K26_BASE_MODEL": (f"{_PKG}.kimi_k2_6_starter", "KIMI_K26_BASE_MODEL"),
    "KIMI_K26_CONFIG_SUFFIXES": (
        f"{_PKG}.kimi_k2_6_starter",
        "KIMI_K26_CONFIG_SUFFIXES",
    ),
    "KIMI_K26_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.kimi_k2_6_starter",
        "KIMI_K26_DEFAULT_OUTPUT_DIR",
    ),
    "KIMI_K26_LORA_TARGET_MODULES": (
        f"{_PKG}.kimi_k2_6_starter",
        "KIMI_K26_LORA_TARGET_MODULES",
    ),
    "KIMI_K26_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.kimi_k2_6_starter",
        "KIMI_K26_STARTER_PROFILE_CHOICES",
    ),
    "KIMI_K26_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.kimi_k2_6_starter",
        "KIMI_K26_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "KIMI_K26_SUPPORTED_VARIANTS": (
        f"{_PKG}.kimi_k2_6_starter",
        "KIMI_K26_SUPPORTED_VARIANTS",
    ),
    "KIMI_K26_TASK_CHOICES": (f"{_PKG}.kimi_k2_6_starter", "KIMI_K26_TASK_CHOICES"),
    "KimiK26Config": (f"{_PKG}.kimi_k2_6_starter", "KimiK26Config"),
    "create_kimi_k2_6_agent_config": (
        f"{_PKG}.kimi_k2_6_starter",
        "create_kimi_k2_6_agent_config",
    ),
    "create_kimi_k2_6_preview": (
        f"{_PKG}.kimi_k2_6_starter",
        "create_kimi_k2_6_preview",
    ),
    "describe_kimi_k2_6_starter_profiles": (
        f"{_PKG}.kimi_k2_6_starter",
        "describe_kimi_k2_6_starter_profiles",
    ),
    "finetune_kimi_k2_6": (f"{_PKG}.kimi_k2_6_starter", "finetune_kimi_k2_6"),
    "get_kimi_k2_6_config": (f"{_PKG}.kimi_k2_6_starter", "get_kimi_k2_6_config"),
    "get_kimi_k2_6_gspo_config": (
        f"{_PKG}.kimi_k2_6_starter",
        "get_kimi_k2_6_gspo_config",
    ),
    "get_kimi_k2_6_gspo_overrides": (
        f"{_PKG}.kimi_k2_6_starter",
        "get_kimi_k2_6_gspo_overrides",
    ),
    "get_kimi_k2_6_profile_description": (
        f"{_PKG}.kimi_k2_6_starter",
        "get_kimi_k2_6_profile_description",
    ),
    "get_kimi_k2_6_profile_overrides": (
        f"{_PKG}.kimi_k2_6_starter",
        "get_kimi_k2_6_profile_overrides",
    ),
    "get_kimi_k2_6_system_prompt": (
        f"{_PKG}.kimi_k2_6_starter",
        "get_kimi_k2_6_system_prompt",
    ),
    "load_kimi_k2_6_config_file": (
        f"{_PKG}.kimi_k2_6_starter",
        "load_kimi_k2_6_config_file",
    ),
    "run_kimi_k2_6_config": (f"{_PKG}.kimi_k2_6_starter", "run_kimi_k2_6_config"),
    "summarize_kimi_k2_6_config": (
        f"{_PKG}.kimi_k2_6_starter",
        "summarize_kimi_k2_6_config",
    ),
    "validate_kimi_k2_6_config": (
        f"{_PKG}.kimi_k2_6_starter",
        "validate_kimi_k2_6_config",
    ),
    "write_kimi_k2_6_config_file": (
        f"{_PKG}.kimi_k2_6_starter",
        "write_kimi_k2_6_config_file",
    ),
    # Kimi-K3 starter path
    "KIMI_K3_BASE_MODEL": (f"{_PKG}.kimi_k3_starter", "KIMI_K3_BASE_MODEL"),
    "KIMI_K3_CONFIG_SUFFIXES": (
        f"{_PKG}.kimi_k3_starter",
        "KIMI_K3_CONFIG_SUFFIXES",
    ),
    "KIMI_K3_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.kimi_k3_starter",
        "KIMI_K3_DEFAULT_OUTPUT_DIR",
    ),
    "KIMI_K3_LORA_TARGET_MODULES": (
        f"{_PKG}.kimi_k3_starter",
        "KIMI_K3_LORA_TARGET_MODULES",
    ),
    "KIMI_K3_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.kimi_k3_starter",
        "KIMI_K3_STARTER_PROFILE_CHOICES",
    ),
    "KIMI_K3_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.kimi_k3_starter",
        "KIMI_K3_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "KIMI_K3_SUPPORTED_VARIANTS": (
        f"{_PKG}.kimi_k3_starter",
        "KIMI_K3_SUPPORTED_VARIANTS",
    ),
    "KIMI_K3_TASK_CHOICES": (f"{_PKG}.kimi_k3_starter", "KIMI_K3_TASK_CHOICES"),
    "KimiK3Config": (f"{_PKG}.kimi_k3_starter", "KimiK3Config"),
    "create_kimi_k3_agent_config": (
        f"{_PKG}.kimi_k3_starter",
        "create_kimi_k3_agent_config",
    ),
    "create_kimi_k3_preview": (f"{_PKG}.kimi_k3_starter", "create_kimi_k3_preview"),
    "describe_kimi_k3_starter_profiles": (
        f"{_PKG}.kimi_k3_starter",
        "describe_kimi_k3_starter_profiles",
    ),
    "finetune_kimi_k3": (f"{_PKG}.kimi_k3_starter", "finetune_kimi_k3"),
    "get_kimi_k3_config": (f"{_PKG}.kimi_k3_starter", "get_kimi_k3_config"),
    "get_kimi_k3_gspo_config": (
        f"{_PKG}.kimi_k3_starter",
        "get_kimi_k3_gspo_config",
    ),
    "get_kimi_k3_gspo_overrides": (
        f"{_PKG}.kimi_k3_starter",
        "get_kimi_k3_gspo_overrides",
    ),
    "get_kimi_k3_profile_description": (
        f"{_PKG}.kimi_k3_starter",
        "get_kimi_k3_profile_description",
    ),
    "get_kimi_k3_profile_overrides": (
        f"{_PKG}.kimi_k3_starter",
        "get_kimi_k3_profile_overrides",
    ),
    "get_kimi_k3_system_prompt": (
        f"{_PKG}.kimi_k3_starter",
        "get_kimi_k3_system_prompt",
    ),
    "load_kimi_k3_config_file": (
        f"{_PKG}.kimi_k3_starter",
        "load_kimi_k3_config_file",
    ),
    "run_kimi_k3_config": (f"{_PKG}.kimi_k3_starter", "run_kimi_k3_config"),
    "summarize_kimi_k3_config": (
        f"{_PKG}.kimi_k3_starter",
        "summarize_kimi_k3_config",
    ),
    "validate_kimi_k3_config": (
        f"{_PKG}.kimi_k3_starter",
        "validate_kimi_k3_config",
    ),
    "write_kimi_k3_config_file": (
        f"{_PKG}.kimi_k3_starter",
        "write_kimi_k3_config_file",
    ),
    # Muse Glimmer starter path
    "MUSE_GLIMMER_BASE_MODEL": (
        f"{_PKG}.muse_glimmer_starter",
        "MUSE_GLIMMER_BASE_MODEL",
    ),
    "MUSE_GLIMMER_CONFIG_SUFFIXES": (
        f"{_PKG}.muse_glimmer_starter",
        "MUSE_GLIMMER_CONFIG_SUFFIXES",
    ),
    "MUSE_GLIMMER_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.muse_glimmer_starter",
        "MUSE_GLIMMER_DEFAULT_OUTPUT_DIR",
    ),
    "MUSE_GLIMMER_LORA_TARGET_MODULES": (
        f"{_PKG}.muse_glimmer_starter",
        "MUSE_GLIMMER_LORA_TARGET_MODULES",
    ),
    "MUSE_GLIMMER_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.muse_glimmer_starter",
        "MUSE_GLIMMER_STARTER_PROFILE_CHOICES",
    ),
    "MUSE_GLIMMER_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.muse_glimmer_starter",
        "MUSE_GLIMMER_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "MUSE_GLIMMER_SUPPORTED_VARIANTS": (
        f"{_PKG}.muse_glimmer_starter",
        "MUSE_GLIMMER_SUPPORTED_VARIANTS",
    ),
    "MUSE_GLIMMER_TASK_CHOICES": (
        f"{_PKG}.muse_glimmer_starter",
        "MUSE_GLIMMER_TASK_CHOICES",
    ),
    "MuseGlimmerConfig": (f"{_PKG}.muse_glimmer_starter", "MuseGlimmerConfig"),
    "create_muse_glimmer_agent_config": (
        f"{_PKG}.muse_glimmer_starter",
        "create_muse_glimmer_agent_config",
    ),
    "create_muse_glimmer_preview": (
        f"{_PKG}.muse_glimmer_starter",
        "create_muse_glimmer_preview",
    ),
    "describe_muse_glimmer_starter_profiles": (
        f"{_PKG}.muse_glimmer_starter",
        "describe_muse_glimmer_starter_profiles",
    ),
    "finetune_muse_glimmer": (
        f"{_PKG}.muse_glimmer_starter",
        "finetune_muse_glimmer",
    ),
    "get_muse_glimmer_config": (
        f"{_PKG}.muse_glimmer_starter",
        "get_muse_glimmer_config",
    ),
    "get_muse_glimmer_gspo_config": (
        f"{_PKG}.muse_glimmer_starter",
        "get_muse_glimmer_gspo_config",
    ),
    "get_muse_glimmer_gspo_overrides": (
        f"{_PKG}.muse_glimmer_starter",
        "get_muse_glimmer_gspo_overrides",
    ),
    "get_muse_glimmer_profile_description": (
        f"{_PKG}.muse_glimmer_starter",
        "get_muse_glimmer_profile_description",
    ),
    "get_muse_glimmer_profile_overrides": (
        f"{_PKG}.muse_glimmer_starter",
        "get_muse_glimmer_profile_overrides",
    ),
    "get_muse_glimmer_system_prompt": (
        f"{_PKG}.muse_glimmer_starter",
        "get_muse_glimmer_system_prompt",
    ),
    "load_muse_glimmer_config_file": (
        f"{_PKG}.muse_glimmer_starter",
        "load_muse_glimmer_config_file",
    ),
    "run_muse_glimmer_config": (
        f"{_PKG}.muse_glimmer_starter",
        "run_muse_glimmer_config",
    ),
    "summarize_muse_glimmer_config": (
        f"{_PKG}.muse_glimmer_starter",
        "summarize_muse_glimmer_config",
    ),
    "validate_muse_glimmer_config": (
        f"{_PKG}.muse_glimmer_starter",
        "validate_muse_glimmer_config",
    ),
    "write_muse_glimmer_config_file": (
        f"{_PKG}.muse_glimmer_starter",
        "write_muse_glimmer_config_file",
    ),
    # Nemotron 3.5 starter path
    "NEMOTRON_3_5_BASE_MODEL": (
        f"{_PKG}.nemotron_3_5_starter",
        "NEMOTRON_3_5_BASE_MODEL",
    ),
    "NEMOTRON_3_5_CONFIG_SUFFIXES": (
        f"{_PKG}.nemotron_3_5_starter",
        "NEMOTRON_3_5_CONFIG_SUFFIXES",
    ),
    "NEMOTRON_3_5_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.nemotron_3_5_starter",
        "NEMOTRON_3_5_DEFAULT_OUTPUT_DIR",
    ),
    "NEMOTRON_3_5_LORA_TARGET_MODULES": (
        f"{_PKG}.nemotron_3_5_starter",
        "NEMOTRON_3_5_LORA_TARGET_MODULES",
    ),
    "NEMOTRON_3_5_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.nemotron_3_5_starter",
        "NEMOTRON_3_5_STARTER_PROFILE_CHOICES",
    ),
    "NEMOTRON_3_5_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.nemotron_3_5_starter",
        "NEMOTRON_3_5_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "NEMOTRON_3_5_SUPPORTED_VARIANTS": (
        f"{_PKG}.nemotron_3_5_starter",
        "NEMOTRON_3_5_SUPPORTED_VARIANTS",
    ),
    "NEMOTRON_3_5_TASK_CHOICES": (
        f"{_PKG}.nemotron_3_5_starter",
        "NEMOTRON_3_5_TASK_CHOICES",
    ),
    "Nemotron35Config": (f"{_PKG}.nemotron_3_5_starter", "Nemotron35Config"),
    "create_nemotron_3_5_agent_config": (
        f"{_PKG}.nemotron_3_5_starter",
        "create_nemotron_3_5_agent_config",
    ),
    "create_nemotron_3_5_preview": (
        f"{_PKG}.nemotron_3_5_starter",
        "create_nemotron_3_5_preview",
    ),
    "describe_nemotron_3_5_starter_profiles": (
        f"{_PKG}.nemotron_3_5_starter",
        "describe_nemotron_3_5_starter_profiles",
    ),
    "finetune_nemotron_3_5": (
        f"{_PKG}.nemotron_3_5_starter",
        "finetune_nemotron_3_5",
    ),
    "get_nemotron_3_5_config": (
        f"{_PKG}.nemotron_3_5_starter",
        "get_nemotron_3_5_config",
    ),
    "get_nemotron_3_5_gspo_config": (
        f"{_PKG}.nemotron_3_5_starter",
        "get_nemotron_3_5_gspo_config",
    ),
    "get_nemotron_3_5_gspo_overrides": (
        f"{_PKG}.nemotron_3_5_starter",
        "get_nemotron_3_5_gspo_overrides",
    ),
    "get_nemotron_3_5_profile_description": (
        f"{_PKG}.nemotron_3_5_starter",
        "get_nemotron_3_5_profile_description",
    ),
    "get_nemotron_3_5_profile_overrides": (
        f"{_PKG}.nemotron_3_5_starter",
        "get_nemotron_3_5_profile_overrides",
    ),
    "get_nemotron_3_5_system_prompt": (
        f"{_PKG}.nemotron_3_5_starter",
        "get_nemotron_3_5_system_prompt",
    ),
    "load_nemotron_3_5_config_file": (
        f"{_PKG}.nemotron_3_5_starter",
        "load_nemotron_3_5_config_file",
    ),
    "run_nemotron_3_5_config": (
        f"{_PKG}.nemotron_3_5_starter",
        "run_nemotron_3_5_config",
    ),
    "summarize_nemotron_3_5_config": (
        f"{_PKG}.nemotron_3_5_starter",
        "summarize_nemotron_3_5_config",
    ),
    "validate_nemotron_3_5_config": (
        f"{_PKG}.nemotron_3_5_starter",
        "validate_nemotron_3_5_config",
    ),
    "write_nemotron_3_5_config_file": (
        f"{_PKG}.nemotron_3_5_starter",
        "write_nemotron_3_5_config_file",
    ),
    # Qwen3.8 27B starter path
    "QWEN38_27B_BASE_MODEL": (
        f"{_PKG}.qwen3_8_starter",
        "QWEN38_27B_BASE_MODEL",
    ),
    "QWEN38_27B_CONFIG_SUFFIXES": (
        f"{_PKG}.qwen3_8_starter",
        "QWEN38_27B_CONFIG_SUFFIXES",
    ),
    "QWEN38_27B_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.qwen3_8_starter",
        "QWEN38_27B_DEFAULT_OUTPUT_DIR",
    ),
    "QWEN38_27B_LORA_TARGET_MODULES": (
        f"{_PKG}.qwen3_8_starter",
        "QWEN38_27B_LORA_TARGET_MODULES",
    ),
    "QWEN38_27B_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.qwen3_8_starter",
        "QWEN38_27B_STARTER_PROFILE_CHOICES",
    ),
    "QWEN38_27B_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.qwen3_8_starter",
        "QWEN38_27B_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "QWEN38_27B_SUPPORTED_VARIANTS": (
        f"{_PKG}.qwen3_8_starter",
        "QWEN38_27B_SUPPORTED_VARIANTS",
    ),
    "QWEN38_27B_TASK_CHOICES": (
        f"{_PKG}.qwen3_8_starter",
        "QWEN38_27B_TASK_CHOICES",
    ),
    "Qwen38Config": (f"{_PKG}.qwen3_8_starter", "Qwen38Config"),
    "create_qwen3_8_agent_config": (
        f"{_PKG}.qwen3_8_starter",
        "create_qwen3_8_agent_config",
    ),
    "create_qwen3_8_preview": (
        f"{_PKG}.qwen3_8_starter",
        "create_qwen3_8_preview",
    ),
    "describe_qwen3_8_starter_profiles": (
        f"{_PKG}.qwen3_8_starter",
        "describe_qwen3_8_starter_profiles",
    ),
    "finetune_qwen3_8": (
        f"{_PKG}.qwen3_8_starter",
        "finetune_qwen3_8",
    ),
    "get_qwen3_8_config": (
        f"{_PKG}.qwen3_8_starter",
        "get_qwen3_8_config",
    ),
    "get_qwen3_8_gspo_config": (
        f"{_PKG}.qwen3_8_starter",
        "get_qwen3_8_gspo_config",
    ),
    "get_qwen3_8_gspo_overrides": (
        f"{_PKG}.qwen3_8_starter",
        "get_qwen3_8_gspo_overrides",
    ),
    "get_qwen3_8_profile_description": (
        f"{_PKG}.qwen3_8_starter",
        "get_qwen3_8_profile_description",
    ),
    "get_qwen3_8_profile_overrides": (
        f"{_PKG}.qwen3_8_starter",
        "get_qwen3_8_profile_overrides",
    ),
    "get_qwen3_8_system_prompt": (
        f"{_PKG}.qwen3_8_starter",
        "get_qwen3_8_system_prompt",
    ),
    "load_qwen3_8_config_file": (
        f"{_PKG}.qwen3_8_starter",
        "load_qwen3_8_config_file",
    ),
    "run_qwen3_8_config": (
        f"{_PKG}.qwen3_8_starter",
        "run_qwen3_8_config",
    ),
    "summarize_qwen3_8_config": (
        f"{_PKG}.qwen3_8_starter",
        "summarize_qwen3_8_config",
    ),
    "validate_qwen3_8_config": (
        f"{_PKG}.qwen3_8_starter",
        "validate_qwen3_8_config",
    ),
    "write_qwen3_8_config_file": (
        f"{_PKG}.qwen3_8_starter",
        "write_qwen3_8_config_file",
    ),
    # Qwen3 Coder starter path
    "QWEN3_CODER_BASE_MODEL": (
        f"{_PKG}.qwen3_coder_starter",
        "QWEN3_CODER_BASE_MODEL",
    ),
    "QWEN3_CODER_CONFIG_SUFFIXES": (
        f"{_PKG}.qwen3_coder_starter",
        "QWEN3_CODER_CONFIG_SUFFIXES",
    ),
    "QWEN3_CODER_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.qwen3_coder_starter",
        "QWEN3_CODER_DEFAULT_OUTPUT_DIR",
    ),
    "QWEN3_CODER_LORA_TARGET_MODULES": (
        f"{_PKG}.qwen3_coder_starter",
        "QWEN3_CODER_LORA_TARGET_MODULES",
    ),
    "QWEN3_CODER_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.qwen3_coder_starter",
        "QWEN3_CODER_STARTER_PROFILE_CHOICES",
    ),
    "QWEN3_CODER_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.qwen3_coder_starter",
        "QWEN3_CODER_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "QWEN3_CODER_SUPPORTED_VARIANTS": (
        f"{_PKG}.qwen3_coder_starter",
        "QWEN3_CODER_SUPPORTED_VARIANTS",
    ),
    "QWEN3_CODER_TASK_CHOICES": (
        f"{_PKG}.qwen3_coder_starter",
        "QWEN3_CODER_TASK_CHOICES",
    ),
    "Qwen3CoderConfig": (f"{_PKG}.qwen3_coder_starter", "Qwen3CoderConfig"),
    "create_qwen3_coder_agent_config": (
        f"{_PKG}.qwen3_coder_starter",
        "create_qwen3_coder_agent_config",
    ),
    "create_qwen3_coder_preview": (
        f"{_PKG}.qwen3_coder_starter",
        "create_qwen3_coder_preview",
    ),
    "describe_qwen3_coder_starter_profiles": (
        f"{_PKG}.qwen3_coder_starter",
        "describe_qwen3_coder_starter_profiles",
    ),
    "finetune_qwen3_coder": (f"{_PKG}.qwen3_coder_starter", "finetune_qwen3_coder"),
    "get_qwen3_coder_config": (
        f"{_PKG}.qwen3_coder_starter",
        "get_qwen3_coder_config",
    ),
    "get_qwen3_coder_gspo_config": (
        f"{_PKG}.qwen3_coder_starter",
        "get_qwen3_coder_gspo_config",
    ),
    "get_qwen3_coder_gspo_overrides": (
        f"{_PKG}.qwen3_coder_starter",
        "get_qwen3_coder_gspo_overrides",
    ),
    "get_qwen3_coder_profile_description": (
        f"{_PKG}.qwen3_coder_starter",
        "get_qwen3_coder_profile_description",
    ),
    "get_qwen3_coder_profile_overrides": (
        f"{_PKG}.qwen3_coder_starter",
        "get_qwen3_coder_profile_overrides",
    ),
    "get_qwen3_coder_system_prompt": (
        f"{_PKG}.qwen3_coder_starter",
        "get_qwen3_coder_system_prompt",
    ),
    "load_qwen3_coder_config_file": (
        f"{_PKG}.qwen3_coder_starter",
        "load_qwen3_coder_config_file",
    ),
    "run_qwen3_coder_config": (
        f"{_PKG}.qwen3_coder_starter",
        "run_qwen3_coder_config",
    ),
    "summarize_qwen3_coder_config": (
        f"{_PKG}.qwen3_coder_starter",
        "summarize_qwen3_coder_config",
    ),
    "validate_qwen3_coder_config": (
        f"{_PKG}.qwen3_coder_starter",
        "validate_qwen3_coder_config",
    ),
    "write_qwen3_coder_config_file": (
        f"{_PKG}.qwen3_coder_starter",
        "write_qwen3_coder_config_file",
    ),
    # gpt-oss starter path
    "GPT_OSS_120B_MODEL": (f"{_PKG}.gpt_oss_starter", "GPT_OSS_120B_MODEL"),
    "GPT_OSS_BASE_MODEL": (f"{_PKG}.gpt_oss_starter", "GPT_OSS_BASE_MODEL"),
    "GPT_OSS_CONFIG_SUFFIXES": (
        f"{_PKG}.gpt_oss_starter",
        "GPT_OSS_CONFIG_SUFFIXES",
    ),
    "GPT_OSS_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.gpt_oss_starter",
        "GPT_OSS_DEFAULT_OUTPUT_DIR",
    ),
    "GPT_OSS_LORA_TARGET_MODULES": (
        f"{_PKG}.gpt_oss_starter",
        "GPT_OSS_LORA_TARGET_MODULES",
    ),
    "GPT_OSS_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.gpt_oss_starter",
        "GPT_OSS_STARTER_PROFILE_CHOICES",
    ),
    "GPT_OSS_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.gpt_oss_starter",
        "GPT_OSS_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "GPT_OSS_SUPPORTED_VARIANTS": (
        f"{_PKG}.gpt_oss_starter",
        "GPT_OSS_SUPPORTED_VARIANTS",
    ),
    "GPT_OSS_TASK_CHOICES": (f"{_PKG}.gpt_oss_starter", "GPT_OSS_TASK_CHOICES"),
    "GptOssConfig": (f"{_PKG}.gpt_oss_starter", "GptOssConfig"),
    "create_gpt_oss_agent_config": (
        f"{_PKG}.gpt_oss_starter",
        "create_gpt_oss_agent_config",
    ),
    "create_gpt_oss_preview": (f"{_PKG}.gpt_oss_starter", "create_gpt_oss_preview"),
    "describe_gpt_oss_starter_profiles": (
        f"{_PKG}.gpt_oss_starter",
        "describe_gpt_oss_starter_profiles",
    ),
    "finetune_gpt_oss": (f"{_PKG}.gpt_oss_starter", "finetune_gpt_oss"),
    "get_gpt_oss_config": (f"{_PKG}.gpt_oss_starter", "get_gpt_oss_config"),
    "get_gpt_oss_gspo_config": (
        f"{_PKG}.gpt_oss_starter",
        "get_gpt_oss_gspo_config",
    ),
    "get_gpt_oss_gspo_overrides": (
        f"{_PKG}.gpt_oss_starter",
        "get_gpt_oss_gspo_overrides",
    ),
    "get_gpt_oss_profile_description": (
        f"{_PKG}.gpt_oss_starter",
        "get_gpt_oss_profile_description",
    ),
    "get_gpt_oss_profile_overrides": (
        f"{_PKG}.gpt_oss_starter",
        "get_gpt_oss_profile_overrides",
    ),
    "get_gpt_oss_system_prompt": (
        f"{_PKG}.gpt_oss_starter",
        "get_gpt_oss_system_prompt",
    ),
    "load_gpt_oss_config_file": (
        f"{_PKG}.gpt_oss_starter",
        "load_gpt_oss_config_file",
    ),
    "run_gpt_oss_config": (f"{_PKG}.gpt_oss_starter", "run_gpt_oss_config"),
    "summarize_gpt_oss_config": (
        f"{_PKG}.gpt_oss_starter",
        "summarize_gpt_oss_config",
    ),
    "validate_gpt_oss_config": (
        f"{_PKG}.gpt_oss_starter",
        "validate_gpt_oss_config",
    ),
    "write_gpt_oss_config_file": (
        f"{_PKG}.gpt_oss_starter",
        "write_gpt_oss_config_file",
    ),
    # DeepSeek V4 Flash starter path
    "DEEPSEEK_V4_FLASH_BASE_MODEL": (
        f"{_PKG}.deepseek_v4_starter",
        "DEEPSEEK_V4_FLASH_BASE_MODEL",
    ),
    "DEEPSEEK_V4_BASE_MODEL": (
        f"{_PKG}.deepseek_v4_starter",
        "DEEPSEEK_V4_BASE_MODEL",
    ),
    "DEEPSEEK_V4_CONFIG_SUFFIXES": (
        f"{_PKG}.deepseek_v4_starter",
        "DEEPSEEK_V4_CONFIG_SUFFIXES",
    ),
    "DEEPSEEK_V4_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.deepseek_v4_starter",
        "DEEPSEEK_V4_DEFAULT_OUTPUT_DIR",
    ),
    "DEEPSEEK_V4_LORA_TARGET_MODULES": (
        f"{_PKG}.deepseek_v4_starter",
        "DEEPSEEK_V4_LORA_TARGET_MODULES",
    ),
    "DEEPSEEK_V4_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.deepseek_v4_starter",
        "DEEPSEEK_V4_STARTER_PROFILE_CHOICES",
    ),
    "DEEPSEEK_V4_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.deepseek_v4_starter",
        "DEEPSEEK_V4_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "DEEPSEEK_V4_SUPPORTED_VARIANTS": (
        f"{_PKG}.deepseek_v4_starter",
        "DEEPSEEK_V4_SUPPORTED_VARIANTS",
    ),
    "DEEPSEEK_V4_TASK_CHOICES": (
        f"{_PKG}.deepseek_v4_starter",
        "DEEPSEEK_V4_TASK_CHOICES",
    ),
    "DeepseekV4Config": (f"{_PKG}.deepseek_v4_starter", "DeepseekV4Config"),
    "create_deepseek_v4_agent_config": (
        f"{_PKG}.deepseek_v4_starter",
        "create_deepseek_v4_agent_config",
    ),
    "create_deepseek_v4_preview": (
        f"{_PKG}.deepseek_v4_starter",
        "create_deepseek_v4_preview",
    ),
    "describe_deepseek_v4_starter_profiles": (
        f"{_PKG}.deepseek_v4_starter",
        "describe_deepseek_v4_starter_profiles",
    ),
    "finetune_deepseek_v4": (f"{_PKG}.deepseek_v4_starter", "finetune_deepseek_v4"),
    "get_deepseek_v4_config": (
        f"{_PKG}.deepseek_v4_starter",
        "get_deepseek_v4_config",
    ),
    "get_deepseek_v4_gspo_config": (
        f"{_PKG}.deepseek_v4_starter",
        "get_deepseek_v4_gspo_config",
    ),
    "get_deepseek_v4_gspo_overrides": (
        f"{_PKG}.deepseek_v4_starter",
        "get_deepseek_v4_gspo_overrides",
    ),
    "get_deepseek_v4_profile_description": (
        f"{_PKG}.deepseek_v4_starter",
        "get_deepseek_v4_profile_description",
    ),
    "get_deepseek_v4_profile_overrides": (
        f"{_PKG}.deepseek_v4_starter",
        "get_deepseek_v4_profile_overrides",
    ),
    "get_deepseek_v4_system_prompt": (
        f"{_PKG}.deepseek_v4_starter",
        "get_deepseek_v4_system_prompt",
    ),
    "load_deepseek_v4_config_file": (
        f"{_PKG}.deepseek_v4_starter",
        "load_deepseek_v4_config_file",
    ),
    "run_deepseek_v4_config": (
        f"{_PKG}.deepseek_v4_starter",
        "run_deepseek_v4_config",
    ),
    "summarize_deepseek_v4_config": (
        f"{_PKG}.deepseek_v4_starter",
        "summarize_deepseek_v4_config",
    ),
    "validate_deepseek_v4_config": (
        f"{_PKG}.deepseek_v4_starter",
        "validate_deepseek_v4_config",
    ),
    "write_deepseek_v4_config_file": (
        f"{_PKG}.deepseek_v4_starter",
        "write_deepseek_v4_config_file",
    ),
    # Serving artifacts
    "build_serving_manifest": (
        f"{_PKG}.serving_artifacts",
        "build_serving_manifest",
    ),
    "export_merged_model_for_serving": (
        f"{_PKG}.serving_artifacts",
        "export_merged_model_for_serving",
    ),
    "write_serving_manifest": (
        f"{_PKG}.serving_artifacts",
        "write_serving_manifest",
    ),
    # Gemma 4 31B starter path
    "GEMMA4_31B_BASE_MODEL": (f"{_PKG}.gemma4_starter", "GEMMA4_31B_BASE_MODEL"),
    "GEMMA4_31B_CONFIG_SUFFIXES": (
        f"{_PKG}.gemma4_starter",
        "GEMMA4_31B_CONFIG_SUFFIXES",
    ),
    "GEMMA4_31B_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.gemma4_starter",
        "GEMMA4_31B_DEFAULT_OUTPUT_DIR",
    ),
    "GEMMA4_31B_LORA_TARGET_MODULES": (
        f"{_PKG}.gemma4_starter",
        "GEMMA4_31B_LORA_TARGET_MODULES",
    ),
    "GEMMA4_31B_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.gemma4_starter",
        "GEMMA4_31B_STARTER_PROFILE_CHOICES",
    ),
    "GEMMA4_31B_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.gemma4_starter",
        "GEMMA4_31B_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "GEMMA4_31B_SUPPORTED_VARIANTS": (
        f"{_PKG}.gemma4_starter",
        "GEMMA4_31B_SUPPORTED_VARIANTS",
    ),
    "GEMMA4_31B_TASK_CHOICES": (
        f"{_PKG}.gemma4_starter",
        "GEMMA4_31B_TASK_CHOICES",
    ),
    "Gemma4Config": (f"{_PKG}.gemma4_starter", "Gemma4Config"),
    "create_gemma4_31b_agent_config": (
        f"{_PKG}.gemma4_starter",
        "create_gemma4_31b_agent_config",
    ),
    "create_gemma4_31b_preview": (
        f"{_PKG}.gemma4_starter",
        "create_gemma4_31b_preview",
    ),
    "describe_gemma4_31b_starter_profiles": (
        f"{_PKG}.gemma4_starter",
        "describe_gemma4_31b_starter_profiles",
    ),
    "finetune_gemma4_31b": (f"{_PKG}.gemma4_starter", "finetune_gemma4_31b"),
    "get_gemma4_31b_config": (f"{_PKG}.gemma4_starter", "get_gemma4_31b_config"),
    "get_gemma4_31b_gspo_config": (
        f"{_PKG}.gemma4_starter",
        "get_gemma4_31b_gspo_config",
    ),
    "get_gemma4_31b_gspo_overrides": (
        f"{_PKG}.gemma4_starter",
        "get_gemma4_31b_gspo_overrides",
    ),
    "get_gemma4_31b_profile_description": (
        f"{_PKG}.gemma4_starter",
        "get_gemma4_31b_profile_description",
    ),
    "get_gemma4_31b_profile_overrides": (
        f"{_PKG}.gemma4_starter",
        "get_gemma4_31b_profile_overrides",
    ),
    "get_gemma4_31b_system_prompt": (
        f"{_PKG}.gemma4_starter",
        "get_gemma4_31b_system_prompt",
    ),
    "load_gemma4_31b_config_file": (
        f"{_PKG}.gemma4_starter",
        "load_gemma4_31b_config_file",
    ),
    "run_gemma4_31b_config": (f"{_PKG}.gemma4_starter", "run_gemma4_31b_config"),
    "summarize_gemma4_31b_config": (
        f"{_PKG}.gemma4_starter",
        "summarize_gemma4_31b_config",
    ),
    "validate_gemma4_31b_config": (
        f"{_PKG}.gemma4_starter",
        "validate_gemma4_31b_config",
    ),
    "write_gemma4_31b_config_file": (
        f"{_PKG}.gemma4_starter",
        "write_gemma4_31b_config_file",
    ),
    # GLM 5.1 starter path
    "GLM5_1_BASE_MODEL": (f"{_PKG}.glm5_1_starter", "GLM5_1_BASE_MODEL"),
    "GLM5_1_CONFIG_SUFFIXES": (f"{_PKG}.glm5_1_starter", "GLM5_1_CONFIG_SUFFIXES"),
    "GLM5_1_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.glm5_1_starter",
        "GLM5_1_DEFAULT_OUTPUT_DIR",
    ),
    "GLM5_1_FP8_MODEL": (f"{_PKG}.glm5_1_starter", "GLM5_1_FP8_MODEL"),
    "GLM5_1_LORA_TARGET_MODULES": (
        f"{_PKG}.glm5_1_starter",
        "GLM5_1_LORA_TARGET_MODULES",
    ),
    "GLM5_1_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.glm5_1_starter",
        "GLM5_1_STARTER_PROFILE_CHOICES",
    ),
    "GLM5_1_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.glm5_1_starter",
        "GLM5_1_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "GLM5_1_SUPPORTED_VARIANTS": (
        f"{_PKG}.glm5_1_starter",
        "GLM5_1_SUPPORTED_VARIANTS",
    ),
    "GLM5_1_TASK_CHOICES": (f"{_PKG}.glm5_1_starter", "GLM5_1_TASK_CHOICES"),
    "Glm51Config": (f"{_PKG}.glm5_1_starter", "Glm51Config"),
    "create_glm5_1_agent_config": (
        f"{_PKG}.glm5_1_starter",
        "create_glm5_1_agent_config",
    ),
    "create_glm5_1_preview": (f"{_PKG}.glm5_1_starter", "create_glm5_1_preview"),
    "describe_glm5_1_starter_profiles": (
        f"{_PKG}.glm5_1_starter",
        "describe_glm5_1_starter_profiles",
    ),
    "finetune_glm5_1": (f"{_PKG}.glm5_1_starter", "finetune_glm5_1"),
    "get_glm5_1_config": (f"{_PKG}.glm5_1_starter", "get_glm5_1_config"),
    "get_glm5_1_gspo_config": (f"{_PKG}.glm5_1_starter", "get_glm5_1_gspo_config"),
    "get_glm5_1_gspo_overrides": (
        f"{_PKG}.glm5_1_starter",
        "get_glm5_1_gspo_overrides",
    ),
    "get_glm5_1_profile_description": (
        f"{_PKG}.glm5_1_starter",
        "get_glm5_1_profile_description",
    ),
    "get_glm5_1_profile_overrides": (
        f"{_PKG}.glm5_1_starter",
        "get_glm5_1_profile_overrides",
    ),
    "get_glm5_1_serving_recommendations": (
        f"{_PKG}.glm5_1_starter",
        "get_glm5_1_serving_recommendations",
    ),
    "get_glm5_1_system_prompt": (
        f"{_PKG}.glm5_1_starter",
        "get_glm5_1_system_prompt",
    ),
    "load_glm5_1_config_file": (
        f"{_PKG}.glm5_1_starter",
        "load_glm5_1_config_file",
    ),
    "run_glm5_1_config": (f"{_PKG}.glm5_1_starter", "run_glm5_1_config"),
    "summarize_glm5_1_config": (
        f"{_PKG}.glm5_1_starter",
        "summarize_glm5_1_config",
    ),
    "validate_glm5_1_config": (f"{_PKG}.glm5_1_starter", "validate_glm5_1_config"),
    "write_glm5_1_config_file": (
        f"{_PKG}.glm5_1_starter",
        "write_glm5_1_config_file",
    ),
    # GLM 5.2 starter path
    "GLM5_2_BASE_MODEL": (f"{_PKG}.glm5_2_starter", "GLM5_2_BASE_MODEL"),
    "GLM5_2_CONFIG_SUFFIXES": (f"{_PKG}.glm5_2_starter", "GLM5_2_CONFIG_SUFFIXES"),
    "GLM5_2_DEFAULT_OUTPUT_DIR": (
        f"{_PKG}.glm5_2_starter",
        "GLM5_2_DEFAULT_OUTPUT_DIR",
    ),
    "GLM5_2_FP8_MODEL": (f"{_PKG}.glm5_2_starter", "GLM5_2_FP8_MODEL"),
    "GLM5_2_LORA_TARGET_MODULES": (
        f"{_PKG}.glm5_2_starter",
        "GLM5_2_LORA_TARGET_MODULES",
    ),
    "GLM5_2_STARTER_PROFILE_CHOICES": (
        f"{_PKG}.glm5_2_starter",
        "GLM5_2_STARTER_PROFILE_CHOICES",
    ),
    "GLM5_2_STARTER_PROFILE_DESCRIPTIONS": (
        f"{_PKG}.glm5_2_starter",
        "GLM5_2_STARTER_PROFILE_DESCRIPTIONS",
    ),
    "GLM5_2_SUPPORTED_VARIANTS": (
        f"{_PKG}.glm5_2_starter",
        "GLM5_2_SUPPORTED_VARIANTS",
    ),
    "GLM5_2_TASK_CHOICES": (f"{_PKG}.glm5_2_starter", "GLM5_2_TASK_CHOICES"),
    "Glm52Config": (f"{_PKG}.glm5_2_starter", "Glm52Config"),
    "create_glm5_2_agent_config": (
        f"{_PKG}.glm5_2_starter",
        "create_glm5_2_agent_config",
    ),
    "create_glm5_2_preview": (f"{_PKG}.glm5_2_starter", "create_glm5_2_preview"),
    "describe_glm5_2_starter_profiles": (
        f"{_PKG}.glm5_2_starter",
        "describe_glm5_2_starter_profiles",
    ),
    "finetune_glm5_2": (f"{_PKG}.glm5_2_starter", "finetune_glm5_2"),
    "get_glm5_2_config": (f"{_PKG}.glm5_2_starter", "get_glm5_2_config"),
    "get_glm5_2_gspo_config": (f"{_PKG}.glm5_2_starter", "get_glm5_2_gspo_config"),
    "get_glm5_2_gspo_overrides": (
        f"{_PKG}.glm5_2_starter",
        "get_glm5_2_gspo_overrides",
    ),
    "get_glm5_2_profile_description": (
        f"{_PKG}.glm5_2_starter",
        "get_glm5_2_profile_description",
    ),
    "get_glm5_2_profile_overrides": (
        f"{_PKG}.glm5_2_starter",
        "get_glm5_2_profile_overrides",
    ),
    "get_glm5_2_serving_recommendations": (
        f"{_PKG}.glm5_2_starter",
        "get_glm5_2_serving_recommendations",
    ),
    "get_glm5_2_system_prompt": (
        f"{_PKG}.glm5_2_starter",
        "get_glm5_2_system_prompt",
    ),
    "load_glm5_2_config_file": (
        f"{_PKG}.glm5_2_starter",
        "load_glm5_2_config_file",
    ),
    "run_glm5_2_config": (f"{_PKG}.glm5_2_starter", "run_glm5_2_config"),
    "summarize_glm5_2_config": (
        f"{_PKG}.glm5_2_starter",
        "summarize_glm5_2_config",
    ),
    "validate_glm5_2_config": (f"{_PKG}.glm5_2_starter", "validate_glm5_2_config"),
    "write_glm5_2_config_file": (
        f"{_PKG}.glm5_2_starter",
        "write_glm5_2_config_file",
    ),
    "GEPOConfig": (f"{_PKG}.gepo_trainer", "GEPOConfig"),
    "GEPOTrainer": (f"{_PKG}.gepo_trainer", "GEPOTrainer"),
    "train_with_gepo": (f"{_PKG}.gepo_trainer", "train_with_gepo"),
    "DAPOConfig": (f"{_PKG}.dapo_config", "DAPOConfig"),
    "DAPOTrainer": (f"{_PKG}.dapo_trainer", "DAPOTrainer"),
    "DAPORewardShaper": (f"{_PKG}.dapo_trainer", "DAPORewardShaper"),
    "DynamicSamplingBuffer": (f"{_PKG}.dapo_trainer", "DynamicSamplingBuffer"),
    "train_with_dapo": (f"{_PKG}.dapo_entrypoints", "train_with_dapo"),
    "train_reasoning_with_dapo": (
        f"{_PKG}.dapo_entrypoints",
        "train_reasoning_with_dapo",
    ),
    "VAPOConfig": (f"{_PKG}.vapo_trainer", "VAPOConfig"),
    "VAPOTrainer": (f"{_PKG}.vapo_trainer", "VAPOTrainer"),
    "ValueHead": (f"{_PKG}.vapo_trainer", "ValueHead"),
    "LengthAdaptiveGAE": (f"{_PKG}.vapo_trainer", "LengthAdaptiveGAE"),
    "train_with_vapo": (f"{_PKG}.vapo_trainer", "train_with_vapo"),
    # PPO
    "PPOConfig": (f"{_PKG}.ppo_trainer", "PPOConfig"),
    "PPOTrainer": (f"{_PKG}.ppo_trainer", "PPOTrainer"),
    "PPOValueHead": (f"{_PKG}.ppo_trainer", "PPOValueHead"),
    "AdaptiveKLController": (f"{_PKG}.ppo_trainer", "AdaptiveKLController"),
    "compute_gae": (f"{_PKG}.ppo_trainer", "compute_gae"),
    "train_ppo": (f"{_PKG}.ppo_trainer", "train_ppo"),
    # KL controllers
    "KLController": (f"{_PKG}.kl_controllers", "KLController"),
    "FixedKLController": (f"{_PKG}.kl_controllers", "FixedKLController"),
    "LinearKLScheduler": (f"{_PKG}.kl_controllers", "LinearKLScheduler"),
    "CosineKLScheduler": (f"{_PKG}.kl_controllers", "CosineKLScheduler"),
    "WarmupKLScheduler": (f"{_PKG}.kl_controllers", "WarmupKLScheduler"),
    "HybridKLController": (f"{_PKG}.kl_controllers", "HybridKLController"),
    "NoKLController": (f"{_PKG}.kl_controllers", "NoKLController"),
    "create_kl_controller": (f"{_PKG}.kl_controllers", "create_kl_controller"),
    # EMA
    "EMAModel": (f"{_PKG}.ema", "EMAModel"),
    "EMACallback": (f"{_PKG}.ema", "EMACallback"),
    "MultiEMA": (f"{_PKG}.ema", "MultiEMA"),
    "create_ema_model": (f"{_PKG}.ema", "create_ema_model"),
    # RLAIF
    "RLAIFConfig": (f"{_PKG}.rlaif_trainer", "RLAIFConfig"),
    "RLAIFTrainer": (f"{_PKG}.rlaif_trainer", "RLAIFTrainer"),
    "ConstitutionalAI": (f"{_PKG}.rlaif_trainer", "ConstitutionalAI"),
    "train_rlaif": (f"{_PKG}.rlaif_trainer", "train_rlaif"),
    # Offline RL - CQL/IQL
    "CQLConfig": (f"{_PKG}.offline_rl_algorithms", "CQLConfig"),
    "IQLConfig": (f"{_PKG}.offline_rl_algorithms", "IQLConfig"),
    "ConservativeQLearning": (
        f"{_PKG}.offline_rl_algorithms",
        "ConservativeQLearning",
    ),
    "ImplicitQLearning": (f"{_PKG}.offline_rl_algorithms", "ImplicitQLearning"),
    "OfflineRLTrainer": (f"{_PKG}.offline_rl_algorithms", "OfflineRLTrainer"),
    # Offline RL - BCQ
    "BCQConfig": (f"{_PKG}.offline_rl_bcq", "BCQConfig"),
    "BatchConstrainedQLearning": (
        f"{_PKG}.offline_rl_bcq",
        "BatchConstrainedQLearning",
    ),
    "ConversationalVAE": (f"{_PKG}.offline_rl_bcq", "ConversationalVAE"),
    "BCQTrainer": (f"{_PKG}.offline_rl_bcq", "BCQTrainer"),
    # Offline RL - BEAR
    "BEARConfig": (f"{_PKG}.offline_rl_bear", "BEARConfig"),
    "ConversationalBEAR": (f"{_PKG}.offline_rl_bear", "ConversationalBEAR"),
    "MMDKernel": (f"{_PKG}.offline_rl_bear", "MMDKernel"),
    "BEARTrainer": (f"{_PKG}.offline_rl_bear", "BEARTrainer"),
    # Decision Transformer
    "DecisionTransformerConfig": (
        f"{_PKG}.decision_transformer",
        "DecisionTransformerConfig",
    ),
    "DecisionTransformer": (f"{_PKG}.decision_transformer", "DecisionTransformer"),
    "DecisionTransformerTrainer": (
        f"{_PKG}.decision_transformer",
        "DecisionTransformerTrainer",
    ),
    "ConversationEmbedder": (
        f"{_PKG}.decision_transformer",
        "ConversationEmbedder",
    ),
    # Offline GRPO
    "OfflineGRPOConfig": (f"{_PKG}.offline_grpo_trainer", "OfflineGRPOConfig"),
    "OfflineGRPOTrainer": (f"{_PKG}.offline_grpo_trainer", "OfflineGRPOTrainer"),
    "OfflineRLAlgorithm": (f"{_PKG}.offline_grpo_trainer", "OfflineRLAlgorithm"),
    # Domain Randomization
    "DomainRandomizationConfig": (
        f"{_PKG}.domain_randomization",
        "DomainRandomizationConfig",
    ),
    "DomainRandomizer": (f"{_PKG}.domain_randomization", "DomainRandomizer"),
    "PersonaGenerator": (f"{_PKG}.domain_randomization", "PersonaGenerator"),
    "ScenarioGenerator": (f"{_PKG}.domain_randomization", "ScenarioGenerator"),
    "UserPersona": (f"{_PKG}.domain_randomization", "UserPersona"),
    # Sim-to-Real Transfer
    "SimToRealConfig": (f"{_PKG}.sim_to_real", "SimToRealConfig"),
    "SimToRealTransfer": (f"{_PKG}.sim_to_real", "SimToRealTransfer"),
    "UserBehaviorModel": (f"{_PKG}.sim_to_real", "UserBehaviorModel"),
    "DomainAdaptationModule": (f"{_PKG}.sim_to_real", "DomainAdaptationModule"),
}

#: The full public surface of :mod:`stateset_agents.training`, in the order it
#: is advertised.  ``__init__`` re-exports this as ``__all__``; most entries are
#: served lazily by :data:`OPTIONAL_EXPORTS`, the rest are module-level
#: availability flags defined eagerly in ``__init__``.
PUBLIC_NAMES: tuple[str, ...] = (
    "GRPOTrainer",
    "MultiTurnGRPOTrainer",
    "SingleTurnGRPOTrainer",
    "train",
    "TrainingMode",
    "TrainingConfig",
    "TrainingProfile",
    "get_config_for_task",
    "ContinualLearningConfig",
    "ContinualLearningManager",
    "TrajectoryReplayBuffer",
    "EvaluationConfig",
    "evaluate_agent",
    "BACKEND_PROTOCOL",
    "BACKEND_PROTOCOL_VERSION",
    "BackendCapabilities",
    "BackendError",
    "BackendExecutionError",
    "BackendRegistry",
    "BackendResult",
    "CommandTrainingBackend",
    "TrainingBackend",
    "TrainingExperiment",
    "AsyncRolloutClosed",
    "AsyncRolloutConfig",
    "AsyncRolloutCoordinator",
    "AsyncRolloutError",
    "AsyncRolloutStats",
    "AsyncRolloutTimeout",
    "RolloutBatch",
    "RolloutRecord",
    "compute_importance_weights",
    "AsyncRolloutRunResult",
    "AsyncRolloutRuntime",
    "AsyncRolloutRuntimeConfig",
    "AsyncRolloutWorkerError",
    "LearnerStep",
    "PolicyPublisher",
    "RolloutProducer",
    "DistributedRolloutConfig",
    "DistributedRolloutControlPlane",
    "DistributedRolloutStats",
    "WorkerCapacityError",
    "WorkerHealth",
    "WorkerLease",
    "WorkerLeaseError",
    "WorkerLeaseExpired",
    "PolicyArtifact",
    "PolicyArtifactError",
    "PolicyArtifactUnavailable",
    "compute_policy_artifact_sha256",
    "verify_policy_artifact",
    "VLLM_BACKEND_AVAILABLE",
    "TRL_AVAILABLE",
    "GSPO_AVAILABLE",
    "GEPO_AVAILABLE",
    "DAPO_AVAILABLE",
    "VAPO_AVAILABLE",
    "PPO_AVAILABLE",
    "KL_CONTROLLERS_AVAILABLE",
    "EMA_AVAILABLE",
    "RLAIF_AVAILABLE",
    # Offline RL and Sim-to-Real,
    "OFFLINE_RL_AVAILABLE",
    "BCQ_AVAILABLE",
    "BEAR_AVAILABLE",
    "DECISION_TRANSFORMER_AVAILABLE",
    "SIM_TO_REAL_AVAILABLE",
    "AUTO_RESEARCH_AVAILABLE",
    "QWEN35_08B_BASE_MODEL",
    "QWEN35_08B_CONFIG_SUFFIXES",
    "QWEN35_08B_DEFAULT_OUTPUT_DIR",
    "QWEN35_08B_LORA_TARGET_MODULES",
    "QWEN35_08B_POST_TRAINED_MODEL",
    "QWEN35_08B_STARTER_PROFILE_CHOICES",
    "QWEN35_08B_STARTER_PROFILE_DESCRIPTIONS",
    "QWEN35_08B_SUPPORTED_VARIANTS",
    "QWEN35_08B_TASK_CHOICES",
    "Qwen35Config",
    "create_qwen3_5_agent_config",
    "create_qwen3_5_preview",
    "describe_qwen3_5_starter_profiles",
    "finetune_qwen3_5_0_8b",
    "get_qwen3_5_config",
    "get_qwen3_5_gspo_config",
    "get_qwen3_5_gspo_overrides",
    "get_qwen3_5_profile_description",
    "get_qwen3_5_profile_overrides",
    "get_qwen3_5_system_prompt",
    "load_qwen3_5_config_file",
    "run_qwen3_5_0_8b_config",
    "summarize_qwen3_5_config",
    "validate_qwen3_5_config",
    "write_qwen3_5_config_file",
    "KIMI_K26_BASE_MODEL",
    "KIMI_K26_CONFIG_SUFFIXES",
    "KIMI_K26_DEFAULT_OUTPUT_DIR",
    "KIMI_K26_LORA_TARGET_MODULES",
    "KIMI_K26_STARTER_PROFILE_CHOICES",
    "KIMI_K26_STARTER_PROFILE_DESCRIPTIONS",
    "KIMI_K26_SUPPORTED_VARIANTS",
    "KIMI_K26_TASK_CHOICES",
    "KimiK26Config",
    "create_kimi_k2_6_agent_config",
    "create_kimi_k2_6_preview",
    "describe_kimi_k2_6_starter_profiles",
    "finetune_kimi_k2_6",
    "get_kimi_k2_6_config",
    "get_kimi_k2_6_gspo_config",
    "get_kimi_k2_6_gspo_overrides",
    "get_kimi_k2_6_profile_description",
    "get_kimi_k2_6_profile_overrides",
    "get_kimi_k2_6_system_prompt",
    "load_kimi_k2_6_config_file",
    "run_kimi_k2_6_config",
    "summarize_kimi_k2_6_config",
    "validate_kimi_k2_6_config",
    "write_kimi_k2_6_config_file",
    "KIMI_K3_BASE_MODEL",
    "KIMI_K3_CONFIG_SUFFIXES",
    "KIMI_K3_DEFAULT_OUTPUT_DIR",
    "KIMI_K3_LORA_TARGET_MODULES",
    "KIMI_K3_STARTER_PROFILE_CHOICES",
    "KIMI_K3_STARTER_PROFILE_DESCRIPTIONS",
    "KIMI_K3_SUPPORTED_VARIANTS",
    "KIMI_K3_TASK_CHOICES",
    "KimiK3Config",
    "create_kimi_k3_agent_config",
    "create_kimi_k3_preview",
    "describe_kimi_k3_starter_profiles",
    "finetune_kimi_k3",
    "get_kimi_k3_config",
    "get_kimi_k3_gspo_config",
    "get_kimi_k3_gspo_overrides",
    "get_kimi_k3_profile_description",
    "get_kimi_k3_profile_overrides",
    "get_kimi_k3_system_prompt",
    "load_kimi_k3_config_file",
    "run_kimi_k3_config",
    "summarize_kimi_k3_config",
    "validate_kimi_k3_config",
    "write_kimi_k3_config_file",
    "MUSE_GLIMMER_BASE_MODEL",
    "MUSE_GLIMMER_CONFIG_SUFFIXES",
    "MUSE_GLIMMER_DEFAULT_OUTPUT_DIR",
    "MUSE_GLIMMER_LORA_TARGET_MODULES",
    "MUSE_GLIMMER_STARTER_PROFILE_CHOICES",
    "MUSE_GLIMMER_STARTER_PROFILE_DESCRIPTIONS",
    "MUSE_GLIMMER_SUPPORTED_VARIANTS",
    "MUSE_GLIMMER_TASK_CHOICES",
    "MuseGlimmerConfig",
    "create_muse_glimmer_agent_config",
    "create_muse_glimmer_preview",
    "describe_muse_glimmer_starter_profiles",
    "finetune_muse_glimmer",
    "get_muse_glimmer_config",
    "get_muse_glimmer_gspo_config",
    "get_muse_glimmer_gspo_overrides",
    "get_muse_glimmer_profile_description",
    "get_muse_glimmer_profile_overrides",
    "get_muse_glimmer_system_prompt",
    "load_muse_glimmer_config_file",
    "run_muse_glimmer_config",
    "summarize_muse_glimmer_config",
    "validate_muse_glimmer_config",
    "write_muse_glimmer_config_file",
    "NEMOTRON_3_5_BASE_MODEL",
    "NEMOTRON_3_5_CONFIG_SUFFIXES",
    "NEMOTRON_3_5_DEFAULT_OUTPUT_DIR",
    "NEMOTRON_3_5_LORA_TARGET_MODULES",
    "NEMOTRON_3_5_STARTER_PROFILE_CHOICES",
    "NEMOTRON_3_5_STARTER_PROFILE_DESCRIPTIONS",
    "NEMOTRON_3_5_SUPPORTED_VARIANTS",
    "NEMOTRON_3_5_TASK_CHOICES",
    "Nemotron35Config",
    "create_nemotron_3_5_agent_config",
    "create_nemotron_3_5_preview",
    "describe_nemotron_3_5_starter_profiles",
    "finetune_nemotron_3_5",
    "get_nemotron_3_5_config",
    "get_nemotron_3_5_gspo_config",
    "get_nemotron_3_5_gspo_overrides",
    "get_nemotron_3_5_profile_description",
    "get_nemotron_3_5_profile_overrides",
    "get_nemotron_3_5_system_prompt",
    "load_nemotron_3_5_config_file",
    "run_nemotron_3_5_config",
    "summarize_nemotron_3_5_config",
    "validate_nemotron_3_5_config",
    "write_nemotron_3_5_config_file",
    "QWEN38_27B_BASE_MODEL",
    "QWEN38_27B_CONFIG_SUFFIXES",
    "QWEN38_27B_DEFAULT_OUTPUT_DIR",
    "QWEN38_27B_LORA_TARGET_MODULES",
    "QWEN38_27B_STARTER_PROFILE_CHOICES",
    "QWEN38_27B_STARTER_PROFILE_DESCRIPTIONS",
    "QWEN38_27B_SUPPORTED_VARIANTS",
    "QWEN38_27B_TASK_CHOICES",
    "Qwen38Config",
    "create_qwen3_8_agent_config",
    "create_qwen3_8_preview",
    "describe_qwen3_8_starter_profiles",
    "finetune_qwen3_8",
    "get_qwen3_8_config",
    "get_qwen3_8_gspo_config",
    "get_qwen3_8_gspo_overrides",
    "get_qwen3_8_profile_description",
    "get_qwen3_8_profile_overrides",
    "get_qwen3_8_system_prompt",
    "load_qwen3_8_config_file",
    "run_qwen3_8_config",
    "summarize_qwen3_8_config",
    "validate_qwen3_8_config",
    "write_qwen3_8_config_file",
    "QWEN3_CODER_BASE_MODEL",
    "QWEN3_CODER_CONFIG_SUFFIXES",
    "QWEN3_CODER_DEFAULT_OUTPUT_DIR",
    "QWEN3_CODER_LORA_TARGET_MODULES",
    "QWEN3_CODER_STARTER_PROFILE_CHOICES",
    "QWEN3_CODER_STARTER_PROFILE_DESCRIPTIONS",
    "QWEN3_CODER_SUPPORTED_VARIANTS",
    "QWEN3_CODER_TASK_CHOICES",
    "Qwen3CoderConfig",
    "create_qwen3_coder_agent_config",
    "create_qwen3_coder_preview",
    "describe_qwen3_coder_starter_profiles",
    "finetune_qwen3_coder",
    "get_qwen3_coder_config",
    "get_qwen3_coder_gspo_config",
    "get_qwen3_coder_gspo_overrides",
    "get_qwen3_coder_profile_description",
    "get_qwen3_coder_profile_overrides",
    "get_qwen3_coder_system_prompt",
    "load_qwen3_coder_config_file",
    "run_qwen3_coder_config",
    "summarize_qwen3_coder_config",
    "validate_qwen3_coder_config",
    "write_qwen3_coder_config_file",
    "GPT_OSS_120B_MODEL",
    "GPT_OSS_BASE_MODEL",
    "GPT_OSS_CONFIG_SUFFIXES",
    "GPT_OSS_DEFAULT_OUTPUT_DIR",
    "GPT_OSS_LORA_TARGET_MODULES",
    "GPT_OSS_STARTER_PROFILE_CHOICES",
    "GPT_OSS_STARTER_PROFILE_DESCRIPTIONS",
    "GPT_OSS_SUPPORTED_VARIANTS",
    "GPT_OSS_TASK_CHOICES",
    "GptOssConfig",
    "create_gpt_oss_agent_config",
    "create_gpt_oss_preview",
    "describe_gpt_oss_starter_profiles",
    "finetune_gpt_oss",
    "get_gpt_oss_config",
    "get_gpt_oss_gspo_config",
    "get_gpt_oss_gspo_overrides",
    "get_gpt_oss_profile_description",
    "get_gpt_oss_profile_overrides",
    "get_gpt_oss_system_prompt",
    "load_gpt_oss_config_file",
    "run_gpt_oss_config",
    "summarize_gpt_oss_config",
    "validate_gpt_oss_config",
    "write_gpt_oss_config_file",
    "DEEPSEEK_V4_FLASH_BASE_MODEL",
    "DEEPSEEK_V4_BASE_MODEL",
    "DEEPSEEK_V4_CONFIG_SUFFIXES",
    "DEEPSEEK_V4_DEFAULT_OUTPUT_DIR",
    "DEEPSEEK_V4_LORA_TARGET_MODULES",
    "DEEPSEEK_V4_STARTER_PROFILE_CHOICES",
    "DEEPSEEK_V4_STARTER_PROFILE_DESCRIPTIONS",
    "DEEPSEEK_V4_SUPPORTED_VARIANTS",
    "DEEPSEEK_V4_TASK_CHOICES",
    "DeepseekV4Config",
    "create_deepseek_v4_agent_config",
    "create_deepseek_v4_preview",
    "describe_deepseek_v4_starter_profiles",
    "finetune_deepseek_v4",
    "get_deepseek_v4_config",
    "get_deepseek_v4_gspo_config",
    "get_deepseek_v4_gspo_overrides",
    "get_deepseek_v4_profile_description",
    "get_deepseek_v4_profile_overrides",
    "get_deepseek_v4_system_prompt",
    "load_deepseek_v4_config_file",
    "run_deepseek_v4_config",
    "summarize_deepseek_v4_config",
    "validate_deepseek_v4_config",
    "write_deepseek_v4_config_file",
    "build_serving_manifest",
    "export_merged_model_for_serving",
    "write_serving_manifest",
    "GEMMA4_31B_BASE_MODEL",
    "GEMMA4_31B_CONFIG_SUFFIXES",
    "GEMMA4_31B_DEFAULT_OUTPUT_DIR",
    "GEMMA4_31B_LORA_TARGET_MODULES",
    "GEMMA4_31B_STARTER_PROFILE_CHOICES",
    "GEMMA4_31B_STARTER_PROFILE_DESCRIPTIONS",
    "GEMMA4_31B_SUPPORTED_VARIANTS",
    "GEMMA4_31B_TASK_CHOICES",
    "Gemma4Config",
    "create_gemma4_31b_agent_config",
    "create_gemma4_31b_preview",
    "describe_gemma4_31b_starter_profiles",
    "finetune_gemma4_31b",
    "get_gemma4_31b_config",
    "get_gemma4_31b_gspo_config",
    "get_gemma4_31b_gspo_overrides",
    "get_gemma4_31b_profile_description",
    "get_gemma4_31b_profile_overrides",
    "get_gemma4_31b_system_prompt",
    "load_gemma4_31b_config_file",
    "run_gemma4_31b_config",
    "summarize_gemma4_31b_config",
    "validate_gemma4_31b_config",
    "write_gemma4_31b_config_file",
    "GLM5_1_BASE_MODEL",
    "GLM5_1_CONFIG_SUFFIXES",
    "GLM5_1_DEFAULT_OUTPUT_DIR",
    "GLM5_1_FP8_MODEL",
    "GLM5_1_LORA_TARGET_MODULES",
    "GLM5_1_STARTER_PROFILE_CHOICES",
    "GLM5_1_STARTER_PROFILE_DESCRIPTIONS",
    "GLM5_1_SUPPORTED_VARIANTS",
    "GLM5_1_TASK_CHOICES",
    "Glm51Config",
    "create_glm5_1_agent_config",
    "create_glm5_1_preview",
    "describe_glm5_1_starter_profiles",
    "finetune_glm5_1",
    "get_glm5_1_config",
    "get_glm5_1_gspo_config",
    "get_glm5_1_gspo_overrides",
    "get_glm5_1_profile_description",
    "get_glm5_1_profile_overrides",
    "get_glm5_1_serving_recommendations",
    "get_glm5_1_system_prompt",
    "load_glm5_1_config_file",
    "run_glm5_1_config",
    "summarize_glm5_1_config",
    "validate_glm5_1_config",
    "write_glm5_1_config_file",
    "GLM5_2_BASE_MODEL",
    "GLM5_2_CONFIG_SUFFIXES",
    "GLM5_2_DEFAULT_OUTPUT_DIR",
    "GLM5_2_FP8_MODEL",
    "GLM5_2_LORA_TARGET_MODULES",
    "GLM5_2_STARTER_PROFILE_CHOICES",
    "GLM5_2_STARTER_PROFILE_DESCRIPTIONS",
    "GLM5_2_SUPPORTED_VARIANTS",
    "GLM5_2_TASK_CHOICES",
    "Glm52Config",
    "create_glm5_2_agent_config",
    "create_glm5_2_preview",
    "describe_glm5_2_starter_profiles",
    "finetune_glm5_2",
    "get_glm5_2_config",
    "get_glm5_2_gspo_config",
    "get_glm5_2_gspo_overrides",
    "get_glm5_2_profile_description",
    "get_glm5_2_profile_overrides",
    "get_glm5_2_serving_recommendations",
    "get_glm5_2_system_prompt",
    "load_glm5_2_config_file",
    "run_glm5_2_config",
    "summarize_glm5_2_config",
    "validate_glm5_2_config",
    "write_glm5_2_config_file",
)
