import type {
  AlgorithmSummary,
  DatasetSummary,
  EnvironmentPreset,
  ModelSummary,
  TrainingRun,
} from './types';

const now = Date.now();
const minutesAgo = (value: number) => now - value * 60_000;

export const mockRuns: TrainingRun[] = [
  {
    id: 'run-qwen-support-v2',
    name: 'Qwen Support Adapter v2',
    description: 'LoRA fine-tune tuned for customer support escalation control and reward stability.',
    status: 'running',
    baseModel: 'Qwen/Qwen3.5-0.8B-Base',
    datasetName: 'CX Conversations v3',
    owner: 'Mobile Lab',
    preset: 'quality',
    algorithm: 'gspo',
    createdAt: minutesAgo(480),
    updatedAt: minutesAgo(3),
    tags: ['lora', 'support', 'reward-balanced'],
    metrics: {
      avgReward: 0.84,
      bestReward: 0.93,
      loss: 0.31,
      validationLoss: 0.37,
      progressPercent: 62,
      totalEpisodes: 744,
      etaMinutes: 38,
      throughputTokPerSec: 1820,
    },
    config: {
      batchSize: 12,
      learningRate: 1.1e-5,
      numGenerations: 4,
      loraRank: 64,
      quantization: '4-bit',
      maxTurns: 8,
      environment: 'customer_support',
      difficulty: 'hard',
    },
    recentEvents: [
      'Reward variance tightened after KL ramp.',
      'Validation safety metric improved on dispute scenarios.',
      'Checkpoint exported to /outputs/qwen-support-v2/checkpoint-744.',
    ],
    episodes: [
      { id: 'ep-744', episodeNumber: 744, reward: 0.91, status: 'completed', turns: 7, durationMs: 8200, summary: 'Resolved refund dispute with low-risk language.' },
      { id: 'ep-743', episodeNumber: 743, reward: 0.88, status: 'completed', turns: 6, durationMs: 7700, summary: 'Handled damaged-item replacement with concise follow-up.' },
      { id: 'ep-742', episodeNumber: 742, reward: 0.79, status: 'completed', turns: 8, durationMs: 9010, summary: 'Recovered from ambiguous shipping delay prompt.' },
    ],
    source: 'mock',
  },
  {
    id: 'run-llama-returns-v1',
    name: 'Llama Returns Concierge',
    description: 'Queued overnight run for returns workflows with stricter return-policy grounding.',
    status: 'queued',
    baseModel: 'meta-llama/Llama-3.2-3B-Instruct',
    datasetName: 'Returns Edge Cases',
    owner: 'Queue',
    preset: 'balanced',
    algorithm: 'grpo',
    createdAt: minutesAgo(65),
    updatedAt: minutesAgo(12),
    tags: ['queue', 'returns'],
    metrics: {
      avgReward: 0.0,
      bestReward: 0.0,
      loss: 0.0,
      validationLoss: 0.0,
      progressPercent: 7,
      totalEpisodes: 0,
      queueWaitMinutes: 14,
      etaMinutes: 96,
    },
    config: {
      batchSize: 8,
      learningRate: 8e-6,
      numGenerations: 4,
      loraRank: 32,
      quantization: '8-bit',
      maxTurns: 10,
      environment: 'customer_support',
      difficulty: 'medium',
    },
    recentEvents: [
      'GPU slot reserved on a100-2.',
      'Merged eval checklist into launch config.',
      'Awaiting queue drain behind Qwen support run.',
    ],
    episodes: [],
    source: 'mock',
  },
  {
    id: 'run-kimi-routing-v4',
    name: 'Kimi Routing Policy v4',
    description: 'Completed routing-policy pass focused on tool selection and delegation confidence.',
    status: 'completed',
    baseModel: 'moonshotai/Kimi-K2.5',
    datasetName: 'Tool Routing Gold',
    owner: 'Ops',
    preset: 'memory',
    algorithm: 'dapo',
    createdAt: minutesAgo(1440),
    updatedAt: minutesAgo(180),
    tags: ['routing', 'tools', 'checkpoint-ready'],
    metrics: {
      avgReward: 0.89,
      bestReward: 0.97,
      loss: 0.22,
      validationLoss: 0.28,
      progressPercent: 100,
      totalEpisodes: 1200,
      throughputTokPerSec: 2410,
    },
    config: {
      batchSize: 16,
      learningRate: 7.5e-6,
      numGenerations: 6,
      loraRank: 96,
      quantization: '4-bit',
      maxTurns: 6,
      environment: 'rag_agent',
      difficulty: 'expert',
    },
    recentEvents: [
      'Merged adapter passed tool-call eval at 93%.',
      'Checkpoint promoted to deployable shelf.',
      'Regression guardrails stayed green across 5 seeds.',
    ],
    episodes: [
      { id: 'ep-1200', episodeNumber: 1200, reward: 0.96, status: 'completed', turns: 5, durationMs: 6610, summary: 'Selected retrieval tool and summarized citations cleanly.' },
      { id: 'ep-1199', episodeNumber: 1199, reward: 0.94, status: 'completed', turns: 4, durationMs: 6100, summary: 'Routed to docs lookup instead of hallucinating a policy.' },
    ],
    source: 'mock',
  },
  {
    id: 'run-gemma-finance-qa',
    name: 'Gemma Finance QA',
    description: 'Paused run after reward collapse on long-form compliance prompts.',
    status: 'paused',
    baseModel: 'google/gemma-3-4b-it',
    datasetName: 'Finance QA Pack',
    owner: 'Eval',
    preset: 'quality',
    algorithm: 'vapo',
    createdAt: minutesAgo(960),
    updatedAt: minutesAgo(45),
    tags: ['finance', 'paused'],
    metrics: {
      avgReward: 0.57,
      bestReward: 0.82,
      loss: 0.61,
      validationLoss: 0.73,
      progressPercent: 41,
      totalEpisodes: 330,
      etaMinutes: 120,
    },
    config: {
      batchSize: 6,
      learningRate: 6e-6,
      numGenerations: 4,
      loraRank: 48,
      quantization: 'bf16',
      maxTurns: 12,
      environment: 'reasoning',
      difficulty: 'hard',
    },
    recentEvents: [
      'Paused after validation loss spiked for policy-heavy prompts.',
      'Needs curriculum rebalance before resume.',
      'Analyst note: reduce max turns for first phase.',
    ],
    episodes: [
      { id: 'ep-330', episodeNumber: 330, reward: 0.42, status: 'completed', turns: 11, durationMs: 11002, summary: 'Over-explained policy rationale and lost concision reward.' },
    ],
    source: 'mock',
  },
  {
    id: 'run-qwen-rag-grounding',
    name: 'Qwen RAG Grounding Sweep',
    description: 'Failed stress run after dataset packaging omitted citation targets.',
    status: 'failed',
    baseModel: 'Qwen/Qwen3.5-1.7B-Instruct',
    datasetName: 'Docs Grounding Pack',
    owner: 'Infra',
    preset: 'balanced',
    algorithm: 'ppo',
    createdAt: minutesAgo(1880),
    updatedAt: minutesAgo(600),
    tags: ['rag', 'packaging-failure'],
    metrics: {
      avgReward: 0.28,
      bestReward: 0.44,
      loss: 0.94,
      validationLoss: 1.08,
      progressPercent: 19,
      totalEpisodes: 102,
    },
    config: {
      batchSize: 10,
      learningRate: 9e-6,
      numGenerations: 4,
      loraRank: 32,
      quantization: '8-bit',
      maxTurns: 6,
      environment: 'rag_agent',
      difficulty: 'medium',
    },
    recentEvents: [
      'Artifact validation failed: citation span targets missing.',
      'Run archived with failure note for retraining backlog.',
    ],
    episodes: [
      { id: 'ep-102', episodeNumber: 102, reward: 0.16, status: 'failed', turns: 3, durationMs: 4010, summary: 'Could not ground answer due to missing retrieval payload.' },
    ],
    source: 'mock',
  },
];

export const mockDatasets: DatasetSummary[] = [
  {
    id: 'dataset-cx-v3',
    name: 'CX Conversations v3',
    domain: 'customer support',
    status: 'ready',
    tokens: 2_400_000,
    examples: 18_200,
    coverage: 92,
    quality: 95,
    format: 'jsonl',
    updatedAt: minutesAgo(22),
    notes: 'Balanced across refunds, shipping, billing, and escalation recovery.',
  },
  {
    id: 'dataset-routing-gold',
    name: 'Tool Routing Gold',
    domain: 'tool use',
    status: 'ready',
    tokens: 980_000,
    examples: 6_440,
    coverage: 88,
    quality: 97,
    format: 'jsonl',
    updatedAt: minutesAgo(94),
    notes: 'Curated traces for tool selection, refusal, and retrieval fallback.',
  },
  {
    id: 'dataset-returns',
    name: 'Returns Edge Cases',
    domain: 'returns automation',
    status: 'processing',
    tokens: 410_000,
    examples: 2_820,
    coverage: 71,
    quality: 83,
    format: 'parquet',
    updatedAt: minutesAgo(8),
    notes: 'Packaging SKU-level exceptions and double-refund dispute examples.',
  },
  {
    id: 'dataset-finance',
    name: 'Finance QA Pack',
    domain: 'reasoning',
    status: 'needs-review',
    tokens: 1_320_000,
    examples: 9_240,
    coverage: 64,
    quality: 72,
    format: 'jsonl',
    updatedAt: minutesAgo(51),
    notes: 'Needs shorter trajectories and stronger policy alignment labels.',
  },
];

export const mockModels: ModelSummary[] = [
  {
    id: 'model-qwen-base',
    name: 'Qwen 3.5 Base',
    family: 'Qwen',
    role: 'base model',
    status: 'available',
    baseModel: 'Qwen/Qwen3.5-0.8B-Base',
    evalScore: 78,
    latencyMs: 192,
    checkpointType: 'base',
    updatedAt: minutesAgo(10),
    summary: 'Fast starter model for support and routing adapters.',
    tags: ['starter', 'lora-friendly'],
  },
  {
    id: 'model-qwen-support-v2',
    name: 'Qwen Support v2',
    family: 'Qwen',
    role: 'support adapter',
    status: 'training',
    baseModel: 'Qwen/Qwen3.5-0.8B-Base',
    evalScore: 84,
    latencyMs: 210,
    checkpointType: 'lora',
    updatedAt: minutesAgo(3),
    summary: 'Active adapter run focused on policy-safe dispute handling.',
    tags: ['running', 'customer-support'],
  },
  {
    id: 'model-kimi-routing-v4',
    name: 'Kimi Routing v4',
    family: 'Kimi',
    role: 'router',
    status: 'deployed',
    baseModel: 'moonshotai/Kimi-K2.5',
    evalScore: 93,
    latencyMs: 268,
    checkpointType: 'merged',
    updatedAt: minutesAgo(180),
    summary: 'Best performing routing policy with strong citation discipline.',
    tags: ['deployed', 'tools', 'retrieval'],
  },
  {
    id: 'model-llama-returns-v1',
    name: 'Llama Returns v1',
    family: 'Llama',
    role: 'returns concierge',
    status: 'warming',
    baseModel: 'meta-llama/Llama-3.2-3B-Instruct',
    evalScore: 0,
    latencyMs: 0,
    checkpointType: 'queued',
    updatedAt: minutesAgo(12),
    summary: 'Queued launch candidate with stronger refund policy constraints.',
    tags: ['queued', 'returns'],
  },
];

export const mockAlgorithms: AlgorithmSummary[] = [
  { id: 'gspo', name: 'GSPO', description: 'Group self-play optimization for stable preference shaping.' },
  { id: 'grpo', name: 'GRPO', description: 'Grouped relative policy optimization for reward-ranked samples.' },
  { id: 'dapo', name: 'DAPO', description: 'Decoupled advantage policy optimization for routing-heavy runs.' },
  { id: 'vapo', name: 'VAPO', description: 'Variance-aware policy optimization for long-horizon reasoning.' },
];

export const mockEnvironments: EnvironmentPreset[] = [
  { id: 'customer_support', name: 'Customer Support', description: 'Refunds, shipping, billing, and empathy-sensitive escalations.', maxTurnsDefault: 8, difficulty: 'hard' },
  { id: 'rag_agent', name: 'RAG Grounding', description: 'Citation-heavy retrieval tasks and tool routing decisions.', maxTurnsDefault: 6, difficulty: 'expert' },
  { id: 'reasoning', name: 'Reasoning', description: 'Multi-step logic and policy-compliance explanations.', maxTurnsDefault: 12, difficulty: 'hard' },
  { id: 'code_assistant', name: 'Code Assistant', description: 'Implementation help, tool use, and troubleshooting prompts.', maxTurnsDefault: 10, difficulty: 'medium' },
];

export function createMockLaunchRun(): TrainingRun {
  const createdAt = Date.now();
  const timeLabel = new Date(createdAt).toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });

  return {
    id: `mock-launch-${createdAt}`,
    name: `Mobile Sample Run ${timeLabel}`,
    description: 'Preview fine-tune launched locally because the training lab API is unavailable.',
    status: 'running',
    baseModel: 'Qwen/Qwen3.5-0.8B-Base',
    datasetName: 'CX Conversations v3',
    owner: 'Mobile Preview',
    preset: 'balanced',
    algorithm: 'gspo',
    createdAt,
    updatedAt: createdAt,
    tags: ['preview', 'mobile', 'fallback'],
    metrics: {
      avgReward: 0.18,
      bestReward: 0.29,
      loss: 0.91,
      validationLoss: 0.98,
      progressPercent: 4,
      totalEpisodes: 12,
      etaMinutes: 72,
      throughputTokPerSec: 980,
    },
    config: {
      batchSize: 8,
      learningRate: 1e-5,
      numGenerations: 4,
      loraRank: 32,
      quantization: '4-bit',
      maxTurns: 8,
      environment: 'customer_support',
      difficulty: 'medium',
    },
    recentEvents: [
      'Created local preview run from the mobile launcher.',
      'Seeded with fallback metrics until a live backend is reachable.',
      'Reconnect EXPO_PUBLIC_API_BASE_URL to start real runs.',
    ],
    episodes: [
      {
        id: `mock-episode-${createdAt}`,
        episodeNumber: 12,
        reward: 0.29,
        status: 'completed',
        turns: 6,
        durationMs: 6400,
        summary: 'Handled a refund escalation with safe, concise follow-up.',
      },
    ],
    source: 'mock',
  };
}
