name: Benchmark

on:
  push:
    branches: [ main, master ]
    paths:
      - 'stateset_agents/**/*.py'
      - 'grpo_agent_framework/**/*.py'
      - 'benchmarks/**'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'stateset_agents/**/*.py'
      - 'grpo_agent_framework/**/*.py'
      - 'benchmarks/**'
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-benchmark-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-benchmark-
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run benchmarks
      run: |
        python -m pytest benchmarks/ -v --benchmark-json=benchmark-results.json
    
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Python Benchmark
        tool: 'pytest'
        output-file-path: benchmark-results.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
